## APURAÇÃO CAMPANHAS MARÇO 2022
## SANDRO JAKOSKA

library(DBI)
library(tidyverse)
library(lubridate)
library(googlesheets4)
con2 <- dbConnect(odbc::odbc(), "repro2")

CARTOES_ALELO_0422 <- get(load("C:\\Users\\Repro\\Documents\\R\\2022\\CAMPANHAS\\MAR\\CARTOES_ALELO_0422.RData"))

CARTOES_ALELO_0422 <- CARTOES_ALELO_0422 %>% 
  `colnames<-`(c("CODIGO","BPEDIDO","CPF","TIPO","NSERIE","NOME","CENTRO_CUSTO","DATA"))

## ============================================================================================

## G139 SCHROEDER
# Rebate 7% para vendedoras e 3% para montador

CP_G139_0322 <-dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE GCLCODIGO=139),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,CLINOMEFANT,SETOR,GCLCODIGO,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE PEDDTBAIXA BETWEEN
       '03/01/2022' AND '03/31/2022'
      AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N'))


SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
     PROCODIGO,
      PDPDESCRICAO,
       PEDAUTORIZOU,
       SUM(PDPQTDADE) QTD,
       SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
       SUM(PDPUNITLIQUIDO*PDPQTDADE)*0.07 BONUS
       FROM
       PDPRD
       INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
       GROUP BY 1,2,3,4,5,6,7,8") 

View(CP_G139_0322)
CP_G139_0322 %>%  summarize(v=sum(VRVENDA)) # total
CP_G139_0322 %>%  summarize(v=sum(VRVENDA)*0.07) # vendedoras 
CP_G139_0322 %>%  summarize(v=sum(VRVENDA)*0.03) # montador
sum(CP_G139_0322 %>%  summarize(v=sum(VRVENDA)*0.07),CP_G139_0322 %>%  summarize(v=sum(VRVENDA)*0.03)) #total

### Cria Planilha identificação CPFs

CP_G139_0322_IPEDIDOS <- CP_G139_0322 %>% group_by(ID_PEDIDO,PEDDTBAIXA) %>% summarize(VRVENDA=sum(VRVENDA)) %>% 
  as.data.frame() %>% `colnames<-`(c("ID_PEDIDO","DATA","VALOR.VENDA")) %>% 
  mutate(DATA=format(DATA,"%d/%m/%y")) 

range_write("12MXemWUzBpwpiICikn33YtWEKF6zYPUDUbGIBGAtiM8",data=CP_G139_0322_IPEDIDOS,sheet = "MAR22",
            range = "A1") 

## obtem dados planilha identificação CPFs

CPF_G139_CPF_0322 <- read_sheet("12MXemWUzBpwpiICikn33YtWEKF6zYPUDUbGIBGAtiM8",sheet = "MAR22") %>% 
  as.data.frame() %>% 
  mutate(CPF=sub("\\D+", '',CPF)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF))

View(CPF_G139_CPF_0322)


#lista pedidos

LIST_G139_0322 <- inner_join(CP_G139_0322,CPF_G139_CPF_0322,by="ID_PEDIDO") %>% 
  mutate(OBS="SCHROEDER G139 03/22") %>% .[,c(-12,-13,-14)]

View(LIST_G139_0322)

LIST_G139_0322 %>% summarize(BONUS=sum(BONUS)) 


### pagamentos


# Calculo vendedoras
PAG_G139_0322_VENDEDORAS <- LIST_G139_0322 %>% group_by(CPF) %>% summarize(BONUS=sum(BONUS)) 

#calculo com montador

PAG_G139_0322_MONTADOR <- data.frame(CPF=c("88717020930"),BONUS=(CP_G139_0322 %>% summarize(BONUS=sum(VRVENDA)*0.03))) 


PAG_G139_0322 <- left_join(rbind(PAG_G139_0322_VENDEDORAS,PAG_G139_0322_MONTADOR) ,CARTOES_ALELO_0422 %>% 
                             select(NSERIE,CPF),by="CPF") %>%
  .[,c(3,1,2)] %>% mutate(OBS="SCHROEDER G139 03/22") %>%  mutate(CLIENTE='') %>% 
  mutate(GRUPO='139') 

View(PAG_G139_0322)

PAG_G139_0322 %>% summarize(BONUS=sum(BONUS)) 


### ===========================================================================================
## SQL 849 VITAL

CP_849_0322 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO, CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=849),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022'
      AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N'))


SELECT 
      PDPRD.ID_PEDIDO,
       PEDDTBAIXA,
        CLICODIGO,
         GCLCODIGO,
          SETOR,
           PROCODIGO,
            PDPDESCRICAO,
             PEDAUTORIZOU,
              SUM(PDPQTDADE) QTD,
               SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                SUM(PDPUNITLIQUIDO*PDPQTDADE)*0.07 BONUS
                 FROM
                 PDPRD
                 INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
                 GROUP BY 1,2,3,4,5,6,7,8") 

View(CP_849_0322)

CP_849_0322 %>% summarize(v=sum(VRVENDA))

CP_849_0322 %>% summarize(v=sum(VRVENDA)*0.07)

## LISTA PEDIDOS
LIST_849_0322 <- CP_849_0322 %>% 
  mutate(CPF=rep(c("04455447911","06532582913"), length.out=nrow(CP_849_0322))) %>% 
  mutate(OBS="VITAL 849 03/22")


View(LIST_849_0322)

LIST_849_0322 %>% summarize(v=sum(BONUS))


data.frame(CPF=c("04455447911","06532582913"),
           BONUS=(CP_849_0322 %>%
                    summarize(BONUS=round(sum(BONUS)/2,2)))) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

### Pagamentos

PAG_849_0322 <- left_join(data.frame(CPF=c("04455447911","06532582913"),
                                     BONUS=(CP_849_0322 %>%
                                              summarize(BONUS=round(sum(BONUS)/2,2)))),CARTOES_ALELO_0422 %>% 
                            select(NSERIE,CPF),by="CPF") %>% 
  .[,c(3,1,2)] %>% mutate(CLIENTE='849') %>% 
  mutate(GRUPO='') %>% 
  mutate(OBS="VITAL 849 03/22") 

View(PAG_849_0322)

PAG_849_0322 %>% summarize(v=sum(BONUS))
### ===========================================================================================

## SQL 157 DOMBOSCO

CP_157_0322 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=157),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE PEDDTBAIXA BETWEEN  '03/01/2022' AND '03/31/2022'
      AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N'))


SELECT 
      PDPRD.ID_PEDIDO,
       PEDDTBAIXA,
        CLICODIGO,
         GCLCODIGO,
          SETOR,
           PROCODIGO,
            PDPDESCRICAO,
             PEDAUTORIZOU,
              SUM(PDPQTDADE) QTD,
               SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                SUM(PDPUNITLIQUIDO*PDPQTDADE)*0.1 BONUS
                 FROM
                 PDPRD
                 INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
                 GROUP BY 1,2,3,4,5,6,7,8") 

View(CP_157_0322)

CP_157_0322 %>% summarize(v=sum(VRVENDA))

CP_157_0322 %>% summarize(v=sum(VRVENDA)*0.1)


## lista pedidos 
LIST_157_0322 <- CP_157_0322 %>% 
  mutate(CPF=rep(c("03188282940"), length.out=nrow(CP_157_0322))) %>% mutate(OBS="DOM BOSCO 157 03/22")


View(LIST_157_0322)

LIST_157_0322 %>% summarize(v=sum(BONUS))


LIST_157_0322 %>% group_by(CLICODIGO,CPF) %>% summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 


## Pagamento

PAG_157_0322 <- left_join(LIST_157_0322 %>% group_by(CPF) %>% summarize(BONUS=round(sum(BONUS),2)),
                          CARTOES_ALELO_0422 %>% 
                            select(NSERIE,CPF),by="CPF") %>% 
  .[,c(3,1,2)] %>%  mutate(OBS="DOM BOSCO 157 03/22")  %>%  
  mutate(CLIENTE='157') %>%  mutate(GRUPO='')


View(PAG_157_0322)



### ===========================================================================================


## SQL G37 BARBARA K

CP_BC_G37_0322 <-dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO WHERE GCLCODIGO=37),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN  '03/01/2022' AND '03/31/2022'
       AND PEDSITPED <>'C'),


PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE 
         IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)='LA0182' AND PROSITUACAO='A')


SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      CHAVE PROCODIGO,
       (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE) PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(15 AS INTEGER) BONUS
             FROM
              PDPRD
               INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
                INNER JOIN PROD ON PDPRD.PROCODIGO=PROD.PROCODIGO
                 GROUP BY 1,2,3,4,5,6,7,8") %>%  
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF))

View(CP_BC_G37_0322)

CP_BC_G37_0322 %>% summarize(BONUS=sum(BONUS)) 

### LISTA PEDIDOS

LIST_BC_G37_0322 <- CP_BC_G37_0322 %>% filter(!nchar(CPF)<11)  %>% mutate(OBS="AUGUSTO G37 03/22")

View(LIST_BC_G37_0322)

LIST_BC_G37_0322_2 <- CP_BC_G37_0322 %>% mutate(OBS="AUGUSTO G37 03/22")

View(LIST_BC_G37_0322_2)


CP_BC_G37_0322  %>% group_by(CPF) %>% summarize(BONUS=sum(BONUS)) 

### Pagamentos vendedoras

PAG_BC_G37_0322 <- left_join(CP_BC_G37_0322 %>%
                               filter(!nchar(CPF)<11) %>% 
                               group_by(CPF) %>% 
                               summarize(BONUS=round(sum(BONUS),2)),
                             CARTOES_ALELO_0422 %>% 
                               select(NSERIE,CPF),by="CPF") %>%.[,c(3,1,2)] %>% 
  mutate(OBS="AUGUSTO G37 03/22") %>% 
  mutate(CLIENTE='') %>%  mutate(GRUPO='37')

View(PAG_BC_G37_0322)

## Calculo bonificacao gerente

PAG_BC_G37_0322_GERENTE <- left_join(
  data.frame(CPF='06833523932',BONUS=CP_BC_G37_0322 %>% summarize(BONUS=sum(QTD)/2*5)),
  CARTOES_ALELO_0422 %>% 
    select(NSERIE,CPF),by="CPF") %>%.[,c(3,1,2)] %>% 
  mutate(OBS="AUGUSTO G37 03/22") %>% 
  mutate(CLIENTE='') %>%  mutate(GRUPO='37')

View(PAG_BC_G37_0322_GERENTE)

## Calculo coordenadora loja 


PAG_BC_G37_0322_COORD <- left_join(
  data.frame(CPF=c('05059095967','07623027980'),BONUS=c(15,15),CLICODIGO=c(1778,3786)),
  CARTOES_ALELO_0422 %>% 
    select(NSERIE,CPF),by="CPF") %>%  
  mutate(OBS="AUGUSTO G37 03/22") %>% 
  mutate(GRUPO='37') %>% .[,c(4,1,2,5,3,6)] %>% rename(CLIENTE=CLICODIGO) %>% 
  mutate(CLIENTE=as.character(CLIENTE))

View(PAG_BC_G37_0322_COORD )


PAG_BC_G37_0322_4 <- union(PAG_BC_G37_0322,PAG_BC_G37_0322_GERENTE) %>% 
  union(.,PAG_BC_G37_0322_COORD)
View(PAG_BC_G37_0322_4)


### ===========================================================================================

### SQL 4295 LUMITA OTICA

CP_4295_0322 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=4295),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE
       PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=106) -- VR-PRO


SELECT 
    DISTINCT P.ID_PEDIDO,
     PEDDTBAIXA,
       CLICODIGO,
        GCLCODIGO,
         SETOR,
          PEDAUTORIZOU,
           P.PROCODIGO,
            PDPDESCRICAO,
             SUM(PDPQTDADE)QTD,
              SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
               CAST(25 AS INTEGER) BONUS
                FROM
                 PDPRD P
                  INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
                   INNER JOIN PROD1 ON P.PROCODIGO=PROD1.PROCODIGO
                    GROUP BY 1,2,3,4,5,6,7,8") %>%
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 

View(CP_4295_0322)

CP_4295_0322 %>% summarize(v=sum(BONUS))

### LISTAGEM PEDIDOS

LIST_4295_0322 <- CP_4295_0322 %>% mutate(OBS="LUMITA 4295 03/22")

View(LIST_4295_0322)

CP_4295_0322 %>% group_by(CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

### pagamento

PAG_4295_0322 <- left_join(CP_4295_0322 %>% group_by(CPF) %>% summarize(BONUS=round(sum(BONUS),2)),
                           CARTOES_ALELO_0422 %>% 
                             select(NSERIE,CPF),by="CPF") %>% .[,c(3,1,2)] %>% 
  mutate(OBS="LUMITA 4295 03/22") %>%  mutate(CLIENTE='4295') %>%  mutate(GRUPO='') 

View(PAG_4295_0322)


### ===========================================================================================


### SQL G45 OTICA DINIZ NO RESULT

CP_G45_0322 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE GCLCODIGO=45),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=135)

SELECT 
  PDPRD.ID_PEDIDO,
   PEDDTBAIXA,
    CLICODIGO,
     GCLCODIGO,
      SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
         PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(10 AS INTEGER) BONUS
             FROM
              PDPRD
               INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
                INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
                 GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 

View(CP_G45_0322)


CP_G45_0322 %>% summarize(v=sum(BONUS))


## LISTA PEDIDOS
LIST_G45_0322 <- CP_G45_0322 %>% 
  mutate(CPF=rep(c("82323097920"), length.out=nrow(CP_G45_0322))) %>% 
  mutate(OBS="G45 OTICA DINIZ 03/22")

View(LIST_G45_0322)

CP_G45_0322 %>% group_by(CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 


### pagamentos

PAG_G45_0322 <- left_join(LIST_G45_0322 %>% group_by(CPF) %>% 
                            summarize(BONUS=round(sum(BONUS),2)),
                          CARTOES_ALELO_0422 %>% 
                            select(NSERIE,CPF),by="CPF") %>% 
  .[,c(3,1,2)] %>% 
  mutate(OBS="G45 OTICA DINIZ 03/22") %>% 
  mutate(CLIENTE='') %>%  mutate(GRUPO='45') 

View(PAG_G45_0322)

### ===========================================================================================


### SQL 360 OTICA UNIVERSAL

CP_360_0322 <-dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=360),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE
       PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED <>'C'),

PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE 
         IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)='LA0182' AND PROSITUACAO='A') -- BLUE CUT


SELECT 
  DISTINCT PDPRD.ID_PEDIDO,
   PEDDTBAIXA,
    CLICODIGO,
     GCLCODIGO,
      SETOR,
       PEDAUTORIZOU,
        CHAVE PROCODIGO,
         (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE) PDPDESCRICAO,
           SUM(PDPQTDADE)QTD,
            SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
             SUM(PDPQTDADE)/2*10 BONUS
        FROM
        PDPRD
        INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
        INNER JOIN PROD ON PDPRD.PROCODIGO=PROD.PROCODIGO
        GROUP BY 1,2,3,4,5,6,7,8") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 

View(CP_360_0322)

CP_360_0322 %>% summarize(v=sum(BONUS))

#LISTA PEDIDOS
LIST_360_0322 <- CP_360_0322  %>% mutate(OBS="360 OTICA UNIVERSAL 03/22")

View(LIST_360_0322)


CP_360_0322 %>% group_by(CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

## pagamentos

PAG_360_0322 <- left_join(CP_360_0322 %>% group_by(CPF) %>% 
                            summarize(BONUS=round(sum(BONUS),2)),
                          CARTOES_ALELO_0422 %>% 
                            select(NSERIE,CPF),by="CPF") %>% .[,c(3,1,2)] %>% 
  mutate(OBS="360 OTICA UNIVERSAL 03/22") %>%  mutate(CLIENTE='360') %>%  mutate(GRUPO='') 

View(PAG_360_0322)

PAG_360_0322 %>% summarize(v=sum(BONUS))

## ====================================================================================

### SQL 213 OTICA LINO sem resultado

CP_213_0322 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
CLI  AS(SELECT c.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=213),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=128 AND PRODESCRICAO NOT LIKE '%FOTOSSENSIVEL%'), -- UZ

PROD2 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=128 AND PRODESCRICAO LIKE '%FOTOSSENSIVEL%' ), -- UZ PHOTO

PROD3 AS (SELECT PROCODIGO FROM PRODU WHERE PRODESCRICAO LIKE '%ARTLENS%')-- ARTLENS

SELECT 
      PDPRD.ID_PEDIDO,
       PEDDTBAIXA,
        CLICODIGO,
         GCLCODIGO, 
          SETOR,
           PDPRD.PROCODIGO,
            PDPDESCRICAO,
             PEDAUTORIZOU,
              SUM(PDPQTDADE)QTD,
               SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                SUM(PDPQTDADE)/2*20 BONUS
               
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
      PDPRD.ID_PEDIDO,
       PEDDTBAIXA,
        CLICODIGO,
         GCLCODIGO,
          SETOR,
           PDPRD.PROCODIGO,
            PDPDESCRICAO,
             PEDAUTORIZOU,
              SUM(PDPQTDADE)QTD,
               SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                SUM(PDPQTDADE)/2*30 BONUS
               
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
      PDPRD.ID_PEDIDO,
       PEDDTBAIXA,
        CLICODIGO,
         GCLCODIGO,
          SETOR,
           PROD3.PROCODIGO,
            (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PROD3.PROCODIGO),
              PEDAUTORIZOU,
                SUM(PDPQTDADE)QTD,
                 SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                  SUM(PDPQTDADE)/2*20 BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 


View(CP_213_0322)

CP_213_0322 %>% summarize(v=sum(BONUS))

## distribui os CPFs dos participantes nos pedidos
CP_213_0322_2 <- CP_213_0322 %>% 
  mutate(CPF=rep(c("91212766920","06528427984","02235457088","03336880904"), 
                 length.out=nrow(CP_213_0322)))

View(CP_213_0322_2)


LIST_213_0322 <- CP_213_0322_2  %>% mutate(OBS="213 OTICA LINO 03/22") 
View(LIST_213_0322)


CP_213_0322_2 %>% group_by(CLICODIGO,CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) %>% 
  mutate(BONUS=round(sum(BONUS),2)/4)


PAG_213_0322<- left_join(CP_213_0322_2 %>% group_by(CLICODIGO,CPF) %>% 
                           summarize(BONUS=round(sum(BONUS),2)) %>% 
                           mutate(BONUS=round(sum(BONUS),2)/4), CARTOES_ALELO_0422 %>% 
                           select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="OTICA LINO 213 03/22") %>%
  mutate(CLIENTE='213') %>%  mutate(GRUPO='') 

View(PAG_213_0322)



### ===========================================================================================

##  SQL 1419 OTICA LOOK 

CP_1419_0322 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=1419),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=159) ,-- AVANCE


PROD2 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=128 AND LEFT(PROCODIGO,2)='LD') -- UZ+
  
  SELECT 
     PDPRD.ID_PEDIDO,
      PEDDTBAIXA,
       CLICODIGO,
        GCLCODIGO,
         SETOR,
          PDPRD.PROCODIGO,
           PDPDESCRICAO,
            PEDAUTORIZOU,
             SUM(PDPQTDADE)QTD,
              SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
               CAST(20 AS DECIMAL(10,2)) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(5 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 


View(CP_1419_0322)
CP_1419_0322 %>% summarize(v=sum(BONUS))

### lista pedidos  


LIST_1419_0322<- CP_1419_0322 %>% mutate(CPF=rep(c("47751118091"), length.out=nrow(CP_1419_0322))) %>% 
  mutate(OBS="1419 OTICA LOOK 02/21")

View(LIST_1419_0322)


### pagamentos  

PAG_1419_0322 <- left_join(LIST_1419_0322
                           %>%  group_by(CLICODIGO,CPF) %>% 
                             summarize(BONUS=round(sum(BONUS),2)) , CARTOES_ALELO_0422 %>% 
                             select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="1419 OTICA LOOK 01/22") %>% 
  mutate(CLIENTE='1419') %>%  mutate(GRUPO='') 


View(PAG_1419_0322)

## ================================================================================


# SQL 305 GARUVA


CP_305_0322 <-dbGetQuery(con2,"
                           WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO WHERE C.CLICODIGO=305),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,GCLCODIGO,SETOR,PEDID.CLICODIGO,CLINOMEFANT,PEDAUTORIZOU 
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=159), -- AVANCE

PROD2 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=158), -- ACTUALITE

PROD3 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=128), -- UZ+

PROD4 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=135) -- IMAGEM

SELECT  DISTINCT PDPRD.ID_PEDIDO,
          PEDDTBAIXA,
           CLICODIGO,
            GCLCODIGO,
             SETOR,
              PDPRD.PROCODIGO,
               PDPDESCRICAO,
                PEDAUTORIZOU,
                 SUM(PDPQTDADE)QTD,
                  SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                   CAST(40 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
DISTINCT PDPRD.ID_PEDIDO,
          PEDDTBAIXA,
           CLICODIGO,
            GCLCODIGO,
             SETOR,
               PDPRD.PROCODIGO,
               PDPDESCRICAO,
                PEDAUTORIZOU,
                  SUM(PDPQTDADE)QTD,
                   SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                    CAST(30 AS INTEGER) BONUS

FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
DISTINCT PDPRD.ID_PEDIDO,
PEDDTBAIXA,
CLICODIGO,
GCLCODIGO,
SETOR,
PDPRD.PROCODIGO,
PDPDESCRICAO,
 PEDAUTORIZOU,
SUM(PDPQTDADE)QTD,
SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
CAST(20 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
DISTINCT PDPRD.ID_PEDIDO,
PEDDTBAIXA,
CLICODIGO,
GCLCODIGO,
SETOR,
PDPRD.PROCODIGO,
PDPDESCRICAO,
PEDAUTORIZOU,
SUM(PDPQTDADE)QTD,
SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
CAST(10 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2")  %>%  
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF))


View(CP_305_0322)

CP_305_0322 %>% summarize(v=sum(BONUS))


### lista pedidos

LIST_305_0322 <- CP_305_0322 %>% 
  mutate(CPF=rep(c("66655072972"), length.out=nrow(CP_305_0322))) %>% 
  mutate(OBS="305 OTICA GARUVA 03/22")

View(LIST_305_0322)


### pagamentos

PAG_305_0322 <- left_join(LIST_305_0322 %>% group_by(CPF) %>% 
                            summarize(BONUS=round(sum(BONUS),2)),
                          CARTOES_ALELO_0422 %>% 
                            select(NSERIE,CPF),by="CPF") %>% .[,c(3,1,2)] %>% 
  mutate(OBS="305 OTICA GARUVA 03/22")  %>% 
  mutate(CLIENTE='305') %>% 
  mutate(GRUPO='') 

View(PAG_305_0322)
PAG_305_0322 %>% summarize(v=sum(BONUS)) 

## =============================================================================================================         

# SQL G121 RINALDI

CP_G121_0322 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON 
       C.CLICODIGO=A.CLICODIGO WHERE GCLCODIGO=121),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU  
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND (PRODESCRICAO LIKE '%X TRACK%' OR PRODESCRICAO LIKE '%4D%' OR PRODESCRICAO LIKE '%XCLUSIVE%')),

PROD2 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND PRODESCRICAO LIKE '%X DESIGN%'),

PROD3 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND PRODESCRICAO LIKE '%E DESIGN%'),

PROD4 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND (PRODESCRICAO LIKE '%COMFORT%' OR PRODESCRICAO LIKE '%LIBERTY%') AND LEFT(PROCODIGO,2)='LD'),
 
PED_PROMO_PAP AS (SELECT P.ID_PEDIDO ID_PEDIDO_PROMO FROM PDPRD P
 INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
   WHERE PROCODIGO='PAP'),
   
   
PED_PROMO_PLUGIN AS (SELECT ID_PEDIDPROMOCAO ID_PEDIDO_PROMO FROM PEDIDPROMO P
   INNER JOIN PD ON P.ID_PEDIDPROMOCAO=PD.ID_PEDIDO),

PED_PROMO_UNION AS (SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PAP UNION
SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PLUGIN)

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD2.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PROD3.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(40 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION


SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD4.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(30 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2
                      
 ") %>%
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF)) %>% 
  mutate(CPF=sub("\\,", '',CPF)) 

View(CP_G121_0322)

CP_G121_0322 %>% summarize(v=sum(VRVENDA))

CP_G121_0322 %>% summarize(v=sum(BONUS))

### lista pedidos  

LIST_G121_0322 <- CP_G121_0322 %>%  mutate(OBS="RINALDI G121 03/22")


### pagamentos

PAG_G121_0322 <- left_join(CP_G121_0322 %>% group_by(CPF) %>% summarize(BONUS=round(sum(BONUS),2)),
                           CARTOES_ALELO_0422 %>% 
                             select(NSERIE,CPF),by="CPF") %>% 
  .[,c(3,1,2)] %>% 
  mutate(OBS="RINALDI G121 03/22") %>% 
  mutate(CLIENTE='') %>%  mutate(GRUPO='121') 

View(PAG_G121_0322)

PAG_G121_0322 %>% summarize(v=sum(BONUS))



##  SQL 2183 OTICA MADRID --- outros produtos sem resulrtado

CP_2183_0322_2 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=2183),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED <>'C'),

PROD4 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=159) ,-- AVANCE

PROD5 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=158) ,-- ACTUALITE

PROD6 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=128), -- UZ+
  
PROD7 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=135 AND LEFT(PROCODIGO,2)='LD') -- IMAGEM DIGITAL


SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(80 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(70 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD5 ON PDPRD.PROCODIGO=PROD5.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(50 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD6 ON PDPRD.PROCODIGO=PROD6.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(30 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD7 ON PDPRD.PROCODIGO=PROD7.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 


View(CP_2183_0322_2)
CP_2183_0322_2 %>% summarize(v=sum(BONUS))
CP_2183_0322_2 %>% filter(nchar(CPF)==11) %>% summarize(v=sum(BONUS))

### lista pedidos  


LIST_2183_0322_2<- CP_2183_0322_2 %>% filter(nchar(CPF)==11) %>%  mutate(OBS="2183 OTICA MADRID OUTROS 03/22")
View(LIST_2183_0322_2)


## agrupa bonificação CPf

CP_2183_0322_2 %>% group_by(CLICODIGO,CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

### pagamentos  

PAG_2183_0322_2 <- left_join(CP_2183_0322_2 %>% 
                               filter(nchar(CPF)==11) %>%  group_by(CLICODIGO,CPF) %>% 
                               summarize(BONUS=round(sum(BONUS),2)) , CARTOES_ALELO_0422 %>% 
                               select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="2183 OTICA MADRID OUTROS 03/22") %>% 
  mutate(CLIENTE='2183') %>%  mutate(GRUPO='') 


View(PAG_2183_0322_2)


## =============================================================================================================         

# SQL 206 RH

CP_206_0322 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON 
       C.CLICODIGO=A.CLICODIGO WHERE C.CLICODIGO=206),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU  
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND PRODESCRICAO LIKE '%X DESIGN%'),

PROD2 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND PRODESCRICAO LIKE '%E DESIGN%'),

PROD3 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND (PRODESCRICAO LIKE '%COMFORT%' OR PRODESCRICAO LIKE '%LIBERTY%') AND LEFT(PROCODIGO,2)='LD'),
 
PED_PROMO_PAP AS (SELECT P.ID_PEDIDO ID_PEDIDO_PROMO FROM PDPRD P
 INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
   WHERE PROCODIGO='PAP'),

PED_PROMO_PLUGIN AS (SELECT ID_PEDIDPROMOCAO ID_PEDIDO_PROMO FROM PEDIDPROMO P
   INNER JOIN PD ON P.ID_PEDIDPROMOCAO=PD.ID_PEDIDO),

PED_PROMO_UNION AS (SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PAP UNION
SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PLUGIN)

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(40 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD2.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(40 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PROD3.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(20 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 
                      
 ") %>%
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF)) %>% 
  mutate(CPF=sub("\\,", '',CPF)) 

View(CP_206_0322)

CP_206_0322 %>% summarize(v=sum(VRVENDA))

CP_206_0322 %>% summarize(v=sum(BONUS))

### lista pedidos  

LIST_206_0322 <- CP_206_0322 %>% 
  mutate(CPF=rep(c("06850418912"), length.out=nrow(CP_206_0322))) %>% 
  mutate(OBS="206 OTICA RH 03/22")


### pagamentos

PAG_206_0322 <- left_join(LIST_206_0322 %>% group_by(CPF) %>% summarize(BONUS=round(sum(BONUS),2)),
                               CARTOES_ALELO_0422 %>% 
                                 select(NSERIE,CPF),by="CPF") %>% .[,c(3,1,2)] %>% 
  mutate(OBS="206 OTICA RH 03/22") %>% 
  mutate(CLIENTE='206') %>%  mutate(GRUPO='') 

View(PAG_206_0322)


### ===========================================================================================

##  SQL 2183 OTICA MADRID -- Somente Insigne sem resultado

CP_2183_0322_1 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=2183),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED <>'C'),
       
PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%VISION%') ,-- INSIGNE VISION       

PROD2 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%PERFECT%') ,-- INSIGNE PERFECT 

PROD3 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%MORE%') -- INSIGNE MORE 

SELECT 
     PDPRD.ID_PEDIDO,
      PEDDTBAIXA,
       CLICODIGO,
        GCLCODIGO,
         SETOR,
          PDPRD.PROCODIGO,
           PDPDESCRICAO,
            PEDAUTORIZOU,
             SUM(PDPQTDADE)QTD,
              SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
               CAST(120 AS DECIMAL(10,2)) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(100 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(90 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 


View(CP_2183_0322_1)
CP_2183_0322_1 %>% summarize(v=sum(BONUS))
CP_2183_0322_1 %>% filter(nchar(CPF)==11) %>% summarize(v=sum(BONUS))

### lista pedidos  

LIST_2183_0322_1 <- CP_2183_0322_1 %>% filter(nchar(CPF)==11) %>%  
  mutate(OBS="2183 OTICA MADRID INSIGNE 03/22")
View(LIST_2183_0322_1)


## agrupa bonificação CPf

CP_2183_0322_1 %>% group_by(CLICODIGO,CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

### pagamentos  

PAG_2183_0322_1 <- left_join(CP_2183_0322_1 %>% 
                               filter(nchar(CPF)==11) %>%  group_by(CLICODIGO,CPF) %>% 
                               summarize(BONUS=round(sum(BONUS),2)) , CARTOES_ALELO_0422 %>% 
                               select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="2183 OTICA MADRID INSIGNE 03/22") %>% 
  mutate(CLIENTE='2183') %>%  mutate(GRUPO='') 


View(PAG_2183_0322_1)


## =============================================================================================================         

## SQL CAMPANHAS INSIGNE 

CP_INSIGNE_0322 <-dbGetQuery(con2,"
WITH CLI AS (SELECT DISTINCT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR
  FROM CLIEN C
  INNER JOIN (SELECT CLICODIGO FROM CLIPROMO WHERE ID_PROMO=18)CLP ON C.CLICODIGO=CLP.CLICODIGO
  LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
  INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
   WHERE CLICLIENTE='S'),
  
FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
  
PED AS (SELECT ID_PEDIDO,PEDCODIGO,P.CLICODIGO,CLINOMEFANT,GCLCODIGO,PEDDTEMIS,SETOR,
PEDDTBAIXA,PEDORIGEM,TPCODIGO,PEDAUTORIZOU FROM PEDID P
   INNER JOIN FIS F ON P.FISCODIGO1=F.FISCODIGO
    INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
     WHERE PEDDTBAIXA BETWEEN '03/01/2022' AND '03/31/2022' AND PEDSITPED<>'C'),

AUX AS (SELECT PROCODIGO,PROCODIGO2,IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)CHAVE FROM PRODU
WHERE MARCODIGO=189 AND PROTIPO<>'T'),

VALORES_PROMO AS (SELECT PROCODIGO,GRVALORES
FROM NGRUPOS 
 INNER JOIN GRUPOVALORES ON NGRUPOS.GRCODIGO=GRUPOVALORES.GRCODIGO
  WHERE NGRUPOS.GRCODIGO IN (125,127,129,158))
  
SELECT 
PD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
     GCLCODIGO,
      SETOR,
        PD.PROCODIGO,
         PDPDESCRICAO,
          PEDAUTORIZOU,
           CAST(LEFT(GRVALORES,3) AS DOUBLE PRECISION) BONUS,
            SUM(PDPQTDADE) QTD,
             SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA
              
  FROM PDPRD PD
   INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
    INNER JOIN AUX A ON PD.PROCODIGO=A.PROCODIGO
     INNER JOIN VALORES_PROMO ON PD.PROCODIGO=VALORES_PROMO.PROCODIGO 
      GROUP BY 1,2,3,4,5,6,7,8,9 HAVING SUM(PDPQTDADE)>=2
")  %>% mutate(CPF=sub("\\D+", '', PEDAUTORIZOU))  %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF)) %>% 
  mutate(CPF=sub("\\.", '',CPF))  

View(CP_INSIGNE_0322) 

## fix CPF
CP_INSIGNE_0322 %>% filter(nchar(CPF)==10)%>% mutate(CPF='52304892949')

## has CPF
CP_INSIGNE_0322 %>% filter(nchar(CPF)==11) 

## Lino
CP_INSIGNE_0322 %>% filter(CLICODIGO==213) %>% 
  mutate(CPF=rep(c("91212766920","06528427984","02235457088","03336880904"), length.out=nrow(.)))


##union all
LIST_INSIGNE_0322 <- union_all(CP_INSIGNE_0322 %>% filter(nchar(CPF)==10)%>% mutate(CPF='52304892949'),
          CP_INSIGNE_0322 %>% filter(nchar(CPF)==11)) %>% 
  union_all(.,CP_INSIGNE_0322 %>% filter(CLICODIGO==213) %>% 
              mutate(CPF=rep(c("91212766920","06528427984","02235457088","03336880904"), length.out=nrow(.)))) %>% 
  mutate(OBS="CAMPANHA INSIGNE 03/22")


LIST_INSIGNE_0322 %>% filter(GCLCODIGO==285) %>% summarize(v=sum(BONUS))


### Pagamentos


PAG_INSIGNE_0322 <- LIST_INSIGNE_0322 %>% 
  group_by(CLICODIGO,GCLCODIGO,CPF) %>% 
  summarize(BONUS=sum(BONUS)) %>% 
  left_join(.,CARTOES_ALELO_0422 %>% filter(NSERIE!='030000103414415') %>% 
              filter(NSERIE!='030000094247944') %>% 
              select(CPF,NSERIE),by="CPF") %>% 
  mutate(OBS="CAMPANHA INSIGNE 03/22") %>% 
  `colnames<-`(c("CLIENTE","GRUPO","CPF","BONUS","NSERIE","OBS")) %>% 
  .[,c(5,3,4,6,1,2)]

View(PAG_INSIGNE_0322)

PAG_INSIGNE_0322 %>% as.data.frame() %>%  summarize(b=sum(BONUS))

PAG_INSIGNE_0322 %>% .[duplicated(.$CPF),] %>% View()

## =============================================================================================================         
### Pagamentos retroativos

## Pedidos não identificados        

LIST_RETRO_0222 <-read_sheet("1xJz0ESTYV-TEwBgbH2ugFEeSXdjnC6Zo6CRF156LVKs",sheet = "PEDIDOS") %>% 
 mutate(`IDENTIFICAR CPF`=substr(`IDENTIFICAR CPF`,0,11))
  

LIST_RETRO_0222_2 <- LIST_RETRO_0222 %>% mutate(CPF=`IDENTIFICAR CPF`) %>% .[,-14] %>% 
  filter(!is.na(CPF)) %>%  filter(nchar(CPF)==11) %>% 
  mutate(OBS="PAGAMENTO RETROATIVO PEDIDOS NAO IDENTIFICADOS 02/22") 

View(LIST_RETRO_0222_2)  

LIST_RETRO_0222_2 %>% summarize(v=sum(BONUS))


PAG_RETRO_0222 <- LIST_RETRO_0222_2  %>%  filter(!is.na(CPF)) %>%  filter(nchar(CPF)==11) %>% 
  group_by(CPF,CLICODIGO,GCLCODIGO) %>% summarize(BONUS=sum(BONUS)) %>%  
  `colnames<-`(c("CPF","CLIENTE","GRUPO","BONUS")) %>% 
  as.data.frame() %>%
  left_join(.,CARTOES_ALELO_0422 %>% filter(NSERIE!='030000103414415') %>% 
              filter(NSERIE!='030000094247944') %>%  
              select(CPF,NSERIE),by="CPF") %>% 
  mutate(OBS="PAGAMENTO RETROATIVO PEDIDOS NAO IDENTIFICADOS 02/22") %>% .[,c(5,1,4,6,2,3)]
View(PAG_RETRO_0222)  

PAG_RETRO_0222 %>% .[duplicated(.$CPF),] %>% View()


PAG_RETRO_0222 %>% summarize(v=sum(BONUS))



## =============================================================================================================         
## =============================================================================================================         
### PAGAMENTOS FINAL  


PAG_ALL_0322 <-  rbind( 
  PAG_G139_0322, ## schroeder 
  PAG_849_0322,  ## Vital 
  PAG_157_0322, ## Dom bosco 
  PAG_4295_0322, ##lumita
  PAG_360_0322, #universal
  PAG_BC_G37_0322_4, # BK
  PAG_1419_0322, # look
  PAG_305_0322, # garuva
  PAG_G121_0322, # rinaldi
  PAG_206_0322, #RH
  PAG_INSIGNE_0322,
  PAG_RETRO_0222
  ) 

View(PAG_ALL_0322)

PAG_ALL_0322 %>% summarize(v=sum(BONUS))


sheet_write(PAG_ALL_0322,ss="1MXoghPoQ8MXe9e8W-XADgKJDf_44k-L3IA6lTPZCKSw",sheet="PAGAMENTOS")  


## listagem lançamento Alelo

PAG_ALL_0322_2 <- PAG_ALL_0322 %>% group_by(CPF,NSERIE) %>% 
  summarize(BONUS=sum(BONUS))

View(PAG_ALL_0322_2)

PAG_ALL_0322_2 %>% summarize(v=sum(BONUS))

sheet_write(PAG_ALL_0322_2,ss="1MXoghPoQ8MXe9e8W-XADgKJDf_44k-L3IA6lTPZCKSw",sheet="ALELO")  


PAG_ALL_0322_2 %>% .[duplicated(.$CPF),]

## =============================================================================================================         
## =============================================================================================================         
### LISTAGEM FINAL  


LIST_ALL_0322 <-  rbind( 
  LIST_G139_0322,   ## schroeder ok
  LIST_849_0322,    ## Vital ok
  LIST_157_0322,    ## Dom bosco OK
  LIST_BC_G37_0322, ## Barbara K OK
  LIST_4295_0322,   ## Lumita OK
  LIST_360_0322,    ## Universal ok
  LIST_1419_0322,   ##look ok
  LIST_305_0322,    ## Garuva  OK
  LIST_G121_0322,   ## rinaldi OK
  LIST_206_0322, ## RH 
  LIST_INSIGNE_0322, ## Insigne
  LIST_RETRO_0222_2 ##retroativo
) 


View(LIST_ALL_0322)


write.csv2(LIST_ALL_0322,file = "C:/Users/Repro/Documents/R/2022/CAMPANHAS/FEV/LIST_ALL_0322.CSV")

LIST_ALL_0322 %>% summarize(v=sum(BONUS))


sheet_write(LIST_ALL_0322,ss="1MXoghPoQ8MXe9e8W-XADgKJDf_44k-L3IA6lTPZCKSw",sheet="PEDIDOS")       


## =============================================================================================================         
## =============================================================================================================         
### RESUMO  

CP_TOTAL_0322 <- PAG_ALL_0322 %>% summarize(TOTAL=sum(BONUS))    

range_write("1MXoghPoQ8MXe9e8W-XADgKJDf_44k-L3IA6lTPZCKSw",data=CP_TOTAL_0322,sheet = "RESUMO",
            range = "A1")


CP_TOTAL_0322_CLIENTE <- PAG_ALL_0322 %>% filter(is.na(GRUPO)) %>% 
  group_by(CLIENTE) %>% rename("COD"="CLIENTE") %>% summarize(BONUS=sum(BONUS))


CP_TOTAL_0322_CLIENTE %>%  mutate(TIPO='LOJA')  %>% View()

range_write("hhjfP6tEgQDV9UUl8F4-KPMexYU67gdYwj_-A7vMl4",data=CP_TOTAL_0322_CLIENTE,sheet = "RESUMO",
            range = "A5")

CP_TOTAL_0322_GRUPO <- PAG_ALL_0322 %>% filter(!is.na(GRUPO)) %>% 
  group_by(GRUPO) %>%  rename("COD"="GRUPO") %>%  summarize(BONUS=sum(BONUS))


CP_TOTAL_0322_GRUPO %>% filter(str_detect(COD,"\\d+")) %>% mutate(TIPO='GRUPO')  %>% View()


range_write("hhjfP6tEgQDV9UUl8F4-KPMexYU67gdYwj_-A7vMl4",data=CP_TOTAL_0322_GRUPO,sheet = "RESUMO",
            range = "D5")



## =============================================================================================================         
## =============================================================================================================         
### LISTAGEM SETORES 


LIST_ALL_SETORES_0322 <-  rbind( 
  LIST_G139_0322,     ## schroeder ok
  LIST_849_0322,      ## Vital ok
  LIST_157_0322,      ## Dom bosco OK
  LIST_BC_G37_0322_2, ## Barbara K OK
  LIST_4295_0322,     ## Lumita OK
  LIST_G45_0322,      ## Diniz OK 
  LIST_360_0322,      ## Universal ok
  LIST_213_0322,      ## Lino OK
  LIST_1419_0322,     ## lOOK OK  
  LIST_305_0322,      ## Garuva  OK
  LIST_G121_0322,     ## rinaldi OK
  LIST_2183_0322_2,   ## Madrid insigne ok
  LIST_206_0921_0322, ## RH 
  LIST_G195_0821_0122_2,## Luna ok
  LIST_1390_0122,     ##testoni
  LIST_G146_1221_0122,## Marcio Pinheiro ok
  LIST_INSIGNE_0322_SETORES,## Insigne
  LIST_RETRO_0122_2,
  LIST_RETRO_1221_G210
  
  
) 

View(LIST_ALL_SETORES_0322)


sheet_write(LIST_ALL_SETORES_0322,ss="1dirGCDZQmlNTnZfC_gQhiXKE9DAoRNc-2HNWkSfego4",sheet="DADOS")       





