
## APURAÇÃO CAMPANHAS FEVEREIRO 2022
## SANDRO JAKOSKA

library(DBI)
library(tidyverse)
library(lubridate)
library(googlesheets4)
con2 <- dbConnect(odbc::odbc(), "repro2")

CARTOES_ALELO_0322 <- get(load("C:\\Users\\Repro\\Documents\\R\\2022\\CAMPANHAS\\FEV\\CARTOES_ALELO_0322.RData"))

CARTOES_ALELO_0322 <- CARTOES_ALELO_0322 %>% 
  `colnames<-`(c("CODIGO","BPEDIDO","CPF","TIPO","NSERIE","NOME","CENTRO_CUSTO","DATA"))

## ============================================================================================

## G139 SCHROEDER
# Rebate 7% para vendedoras e 3% para montador

CP_G139_0222 <-dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE GCLCODIGO=139),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,CLINOMEFANT,SETOR,GCLCODIGO,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE PEDDTBAIXA BETWEEN
       '02/01/2022' AND '02/28/2022'
      AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N'))


SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
     PROCODIGO,
      PDPDESCRICAO,
       PEDAUTORIZOU,
       SUM(PDPQTDADE) QTD,
       SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
       SUM(PDPUNITLIQUIDO*PDPQTDADE)*0.07 BONUS
       FROM
       PDPRD
       INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
       GROUP BY 1,2,3,4,5,6,7,8") 

View(CP_G139_0222)
CP_G139_0222 %>%  summarize(v=sum(VRVENDA)) # total
CP_G139_0222 %>%  summarize(v=sum(VRVENDA)*0.07) # vendedoras 
CP_G139_0222 %>%  summarize(v=sum(VRVENDA)*0.03) # montador
sum(CP_G139_0222 %>%  summarize(v=sum(VRVENDA)*0.07),CP_G139_0222 %>%  summarize(v=sum(VRVENDA)*0.03)) #total

### Cria Planilha identificação CPFs

CP_G139_0222_IPEDIDOS <- CP_G139_0222 %>% group_by(ID_PEDIDO,PEDDTBAIXA) %>% summarize(VRVENDA=sum(VRVENDA)) %>% 
  as.data.frame() %>% `colnames<-`(c("ID_PEDIDO","DATA","VALOR.VENDA")) %>% 
  mutate(DATA=format(DATA,"%d/%m/%y")) 

range_write("1JhGBSZz9YuSj4Oy2PXPuseurdGIjkaVXNK0fLi2zQwg",data=CP_G139_0222_IPEDIDOS,sheet = "FEV22",
            range = "A1") 

## obtem dados planilha identificação CPFs

CPF_G139_CPF_0222 <- read_sheet("1JhGBSZz9YuSj4Oy2PXPuseurdGIjkaVXNK0fLi2zQwg",sheet = "FEV22") %>% 
  as.data.frame() %>% 
  mutate(CPF=sub("\\D+", '',CPF)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF))

View(CPF_G139_CPF_0222)


#lista pedidos

LIST_G139_0222 <- inner_join(CP_G139_0222,CPF_G139_CPF_0222,by="ID_PEDIDO") %>% 
  mutate(OBS="SCHROEDER G139 02/22") %>% .[,c(-12,-13,-14)]

View(LIST_G139_0222)


### pagamentos


# Calculo vendedoras
PAG_G139_0222_VENDEDORAS <- LIST_G139_0222 %>% group_by(CPF) %>% summarize(BONUS=sum(BONUS)) 

#calculo com montador

PAG_G139_0222_MONTADOR <- data.frame(CPF=c("88717020930"),BONUS=(CP_G139_0222 %>% summarize(BONUS=sum(VRVENDA)*0.03))) 


PAG_G139_0222 <- left_join(rbind(PAG_G139_0222_VENDEDORAS,PAG_G139_0222_MONTADOR) ,CARTOES_ALELO_0322 %>% 
                             select(NSERIE,CPF),by="CPF") %>%
  .[,c(3,1,2)] %>% mutate(OBS="SCHROEDER G139 02/22") %>%  mutate(CLIENTE='') %>% 
  mutate(GRUPO='139') 

View(PAG_G139_0222)

PAG_G139_0222 %>% summarize(BONUS=sum(BONUS)) 


### ===========================================================================================
## SQL 849 VITAL

CP_849_0222 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO, CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=849),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE PEDDTBAIXA BETWEEN '02/01/2022' AND '02/28/2022'
      AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N'))


SELECT 
      PDPRD.ID_PEDIDO,
       PEDDTBAIXA,
        CLICODIGO,
         GCLCODIGO,
          SETOR,
           PROCODIGO,
            PDPDESCRICAO,
             PEDAUTORIZOU,
              SUM(PDPQTDADE) QTD,
               SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                SUM(PDPUNITLIQUIDO*PDPQTDADE)*0.06 BONUS
                 FROM
                 PDPRD
                 INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
                 GROUP BY 1,2,3,4,5,6,7,8") 

View(CP_849_0222)

CP_849_0222 %>% summarize(v=sum(VRVENDA))

CP_849_0222 %>% summarize(v=sum(VRVENDA)*0.06)

## LISTA PEDIDOS
LIST_849_0222 <- CP_849_0222 %>% 
  mutate(CPF=rep(c("04455447911","06532582913"), length.out=nrow(CP_849_0222))) %>% 
  mutate(OBS="VITAL 849 02/22")


View(LIST_849_0222)


data.frame(CPF=c("04455447911","06532582913"),
           BONUS=(CP_849_0222 %>%
                    summarize(BONUS=round(sum(BONUS)/2,2)))) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

### Pagamentos

PAG_849_0222 <- left_join(data.frame(CPF=c("04455447911","06532582913"),
                                     BONUS=(CP_849_0222 %>%
                                              summarize(BONUS=round(sum(BONUS)/2,2)))),CARTOES_ALELO_0322 %>% 
                            select(NSERIE,CPF),by="CPF") %>% 
  .[,c(3,1,2)] %>% mutate(CLIENTE='849') %>% 
  mutate(GRUPO='') %>% 
  mutate(OBS="VITAL 849 02/22") 

View(PAG_849_0222)


### ===========================================================================================

## SQL 157 DOMBOSCO

CP_157_0222 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=157),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE PEDDTBAIXA BETWEEN  '02/01/2022' AND '02/28/2022'
      AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N'))


SELECT 
      PDPRD.ID_PEDIDO,
       PEDDTBAIXA,
        CLICODIGO,
         GCLCODIGO,
          SETOR,
           PROCODIGO,
            PDPDESCRICAO,
             PEDAUTORIZOU,
              SUM(PDPQTDADE) QTD,
               SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                SUM(PDPUNITLIQUIDO*PDPQTDADE)*0.1 BONUS
                 FROM
                 PDPRD
                 INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
                 GROUP BY 1,2,3,4,5,6,7,8") 

View(CP_157_0222)

CP_157_0222 %>% summarize(v=sum(VRVENDA))

CP_157_0222 %>% summarize(v=sum(VRVENDA)*0.1)


## lista pedidos 
LIST_157_0222 <- CP_157_0222 %>% 
  mutate(CPF=rep(c("03188282940"), length.out=nrow(CP_157_0222))) %>% mutate(OBS="DOM BOSCO 157 02/22")


View(LIST_157_0222)

LIST_157_0222 %>% group_by(CLICODIGO,CPF) %>% summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 


## Pagamento

PAG_157_0222 <- left_join(LIST_157_0222 %>% group_by(CPF) %>% summarize(BONUS=round(sum(BONUS),2)),
                          CARTOES_ALELO_0322 %>% 
                            select(NSERIE,CPF),by="CPF") %>% 
  .[,c(3,1,2)] %>%  mutate(OBS="DOM BOSCO 157 02/22")  %>%  
  mutate(CLIENTE='157') %>%  mutate(GRUPO='')


View(PAG_157_0222)



### ===========================================================================================


## SQL G37 BARBARA K

CP_BC_G37_0222 <-dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO WHERE GCLCODIGO=37),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN  '02/01/2022' AND '02/28/2022'
       AND PEDSITPED <>'C'),


PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE 
         IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)='LA0182' AND PROSITUACAO='A')


SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      CHAVE PROCODIGO,
       (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE) PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(15 AS INTEGER) BONUS
             FROM
              PDPRD
               INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
                INNER JOIN PROD ON PDPRD.PROCODIGO=PROD.PROCODIGO
                 GROUP BY 1,2,3,4,5,6,7,8") %>%  
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF))

View(CP_BC_G37_0222)

CP_BC_G37_0222 %>% summarize(BONUS=sum(BONUS)) 

### LISTA PEDIDOS

LIST_BC_G37_0222 <- CP_BC_G37_0222 %>% filter(!nchar(CPF)<11)  %>% mutate(OBS="AUGUSTO G37 02/22")

View(LIST_BC_G37_0222)

LIST_BC_G37_0222_2 <- CP_BC_G37_0222 %>% mutate(OBS="AUGUSTO G37 02/22")

View(LIST_BC_G37_0222_2)


CP_BC_G37_0222  %>% group_by(CPF) %>% summarize(BONUS=sum(BONUS)) 

### Pagamentos vendedoras

PAG_BC_G37_0222 <- left_join(CP_BC_G37_0222 %>%
                               filter(!nchar(CPF)<11) %>% 
                               group_by(CPF) %>% 
                               summarize(BONUS=round(sum(BONUS),2)),
                             CARTOES_ALELO_0322 %>% 
                               select(NSERIE,CPF),by="CPF") %>%.[,c(3,1,2)] %>% 
  mutate(OBS="AUGUSTO G37 01/22") %>% 
  mutate(CLIENTE='') %>%  mutate(GRUPO='37')

View(PAG_BC_G37_0222)

## Calculo bonificacao gerente

PAG_BC_G37_0222_GERENTE <- left_join(
  data.frame(CPF='06833523932',BONUS=CP_BC_G37_0222 %>% summarize(BONUS=sum(QTD)/2*5)),
  CARTOES_ALELO_0322 %>% 
    select(NSERIE,CPF),by="CPF") %>%.[,c(3,1,2)] %>% 
  mutate(OBS="AUGUSTO G37 01/22") %>% 
  mutate(CLIENTE='') %>%  mutate(GRUPO='37')

View(PAG_BC_G37_0222_GERENTE)

## Calculo coordenadora loja 


PAG_BC_G37_0222_COORD <- left_join(
  data.frame(CPF=c('00868166910','07623027980')) %>% 
    cbind(CP_BC_G37_0222 %>% 
            group_by(CLICODIGO) %>% summarize(BONUS=sum(QTD)/2*15)),
  CARTOES_ALELO_0322 %>% 
    select(NSERIE,CPF),by="CPF") %>%  
  mutate(OBS="AUGUSTO G37 01/22") %>% 
  mutate(GRUPO='37') %>% .[,c(4,1,3,5,2,6)] %>% rename(CLIENTE=CLICODIGO) %>% 
  mutate(CLIENTE=as.character(CLIENTE))

View(PAG_BC_G37_0222_COORD )


PAG_BC_G37_0222_4 <- union(PAG_BC_G37_0222,PAG_BC_G37_0222_GERENTE) %>% 
  union(.,PAG_BC_G37_0222_COORD)
View(PAG_BC_G37_0222_4)


### ===========================================================================================

### SQL 4295 LUMITA OTICA

CP_4295_0222 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=4295),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE
       PEDDTBAIXA BETWEEN '02/01/2022' AND '02/28/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=106) -- VR-PRO


SELECT 
    DISTINCT P.ID_PEDIDO,
     PEDDTBAIXA,
       CLICODIGO,
        GCLCODIGO,
         SETOR,
          PEDAUTORIZOU,
           P.PROCODIGO,
            PDPDESCRICAO,
             SUM(PDPQTDADE)QTD,
              SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
               CAST(25 AS INTEGER) BONUS
                FROM
                 PDPRD P
                  INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
                   INNER JOIN PROD1 ON P.PROCODIGO=PROD1.PROCODIGO
                    GROUP BY 1,2,3,4,5,6,7,8") %>%
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 

View(CP_4295_0222)

CP_4295_0222 %>% summarize(v=sum(BONUS))

### LISTAGEM PEDIDOS

LIST_4295_0222 <- CP_4295_0222 %>% mutate(OBS="LUMITA 4295 02/22")

View(LIST_4295_0222)

CP_4295_0222 %>% group_by(CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

### pagamento

PAG_4295_0222 <- left_join(CP_4295_0222 %>% group_by(CPF) %>% summarize(BONUS=round(sum(BONUS),2)),
                           CARTOES_ALELO_0322 %>% 
                             select(NSERIE,CPF),by="CPF") %>% .[,c(3,1,2)] %>% 
  mutate(OBS="LUMITA 4295 02/22") %>%  mutate(CLIENTE='4295') %>%  mutate(GRUPO='') 

View(PAG_4295_0222)


### ===========================================================================================


### SQL G45 OTICA DINIZ INCLUI RETROATIVO JAN/22

CP_G45_0222 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE GCLCODIGO=45),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '01/01/2022' AND '02/28/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=135)

SELECT 
  PDPRD.ID_PEDIDO,
   PEDDTBAIXA,
    CLICODIGO,
     GCLCODIGO,
      SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
         PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(10 AS INTEGER) BONUS
             FROM
              PDPRD
               INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
                INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
                 GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 

View(CP_G45_0222)


CP_G45_0222 %>% summarize(v=sum(BONUS))


## LISTA PEDIDOS
LIST_G45_0222 <- CP_G45_0222 %>% 
  mutate(CPF=rep(c("82323097920"), length.out=nrow(CP_G45_0222))) %>% 
  mutate(OBS="G45 OTICA DINIZ 01/22 - 02/22")

View(LIST_G45_0222)

CP_G45_0222 %>% group_by(CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 


### pagamentos

PAG_G45_0222 <- left_join(LIST_G45_0222 %>% group_by(CPF) %>% 
                            summarize(BONUS=round(sum(BONUS),2)),
                          CARTOES_ALELO_0322 %>% 
                            select(NSERIE,CPF),by="CPF") %>% 
  .[,c(3,1,2)] %>% 
  mutate(OBS="G45 OTICA DINIZ 01/22 - 02/22") %>% 
  mutate(CLIENTE='') %>%  mutate(GRUPO='45') 

View(PAG_G45_0222)

### ===========================================================================================


### SQL 360 OTICA UNIVERSAL

CP_360_0222 <-dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=360),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE
       PEDDTBAIXA BETWEEN '02/01/2022' AND '02/28/2022' AND PEDSITPED <>'C'),

PROD AS (SELECT PROCODIGO,PRODESCRICAO,IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)CHAVE FROM PRODU WHERE 
         IIF(PROCODIGO2 IS NULL, PROCODIGO,PROCODIGO2)='LA0182' AND PROSITUACAO='A') -- BLUE CUT


SELECT 
  DISTINCT PDPRD.ID_PEDIDO,
   PEDDTBAIXA,
    CLICODIGO,
     GCLCODIGO,
      SETOR,
       PEDAUTORIZOU,
        CHAVE PROCODIGO,
         (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=CHAVE) PDPDESCRICAO,
           SUM(PDPQTDADE)QTD,
            SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
             SUM(PDPQTDADE)/2*10 BONUS
        FROM
        PDPRD
        INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
        INNER JOIN PROD ON PDPRD.PROCODIGO=PROD.PROCODIGO
        GROUP BY 1,2,3,4,5,6,7,8") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 

View(CP_360_0222)

CP_360_0222 %>% summarize(v=sum(BONUS))

#LISTA PEDIDOS
LIST_360_0222 <- CP_360_0222  %>% mutate(OBS="360 OTICA UNIVERSAL 02/22")

View(LIST_360_0222)


CP_360_0222 %>% group_by(CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

## pagamentos

PAG_360_0222 <- left_join(CP_360_0222 %>% group_by(CPF) %>% 
                            summarize(BONUS=round(sum(BONUS),2)),
                          CARTOES_ALELO_0322 %>% 
                            select(NSERIE,CPF),by="CPF") %>% .[,c(3,1,2)] %>% 
  mutate(OBS="360 OTICA UNIVERSAL 02/22") %>%  mutate(CLIENTE='360') %>%  mutate(GRUPO='') 

View(PAG_360_0222)

## ====================================================================================

### SQL 213 OTICA LINO

CP_213_0222 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
CLI  AS(SELECT c.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=213),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '02/01/2022' AND '02/28/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=128 AND PRODESCRICAO NOT LIKE '%FOTOSSENSIVEL%'), -- UZ

PROD2 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=128 AND PRODESCRICAO LIKE '%FOTOSSENSIVEL%' ), -- UZ PHOTO

PROD3 AS (SELECT PROCODIGO FROM PRODU WHERE PRODESCRICAO LIKE '%ARTLENS%')-- ARTLENS

SELECT 
      PDPRD.ID_PEDIDO,
       PEDDTBAIXA,
        CLICODIGO,
         GCLCODIGO, 
          SETOR,
           PDPRD.PROCODIGO,
            PDPDESCRICAO,
             PEDAUTORIZOU,
              SUM(PDPQTDADE)QTD,
               SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                SUM(PDPQTDADE)/2*20 BONUS
               
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
      PDPRD.ID_PEDIDO,
       PEDDTBAIXA,
        CLICODIGO,
         GCLCODIGO,
          SETOR,
           PDPRD.PROCODIGO,
            PDPDESCRICAO,
             PEDAUTORIZOU,
              SUM(PDPQTDADE)QTD,
               SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                SUM(PDPQTDADE)/2*30 BONUS
               
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
      PDPRD.ID_PEDIDO,
       PEDDTBAIXA,
        CLICODIGO,
         GCLCODIGO,
          SETOR,
           PROD3.PROCODIGO,
            (SELECT PRODESCRICAO FROM PRODU WHERE PROCODIGO=PROD3.PROCODIGO),
              PEDAUTORIZOU,
                SUM(PDPQTDADE)QTD,
                 SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                  SUM(PDPQTDADE)/2*20 BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 


View(CP_213_0222)

CP_213_0222 %>% summarize(v=sum(BONUS))

## distribui os CPFs dos participantes nos pedidos
CP_213_0222_2 <- CP_213_0222 %>% 
  mutate(CPF=rep(c("91212766920","06528427984","02235457088","03336880904"), 
                 length.out=nrow(CP_213_0222)))

View(CP_213_0222_2)


LIST_213_0222 <- CP_213_0222_2  %>% mutate(OBS="213 OTICA LINO 02/22") 
View(LIST_213_0222)


CP_213_0222_2 %>% group_by(CLICODIGO,CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) %>% 
  mutate(BONUS=round(sum(BONUS),2)/4)


PAG_213_0222<- left_join(CP_213_0222_2 %>% group_by(CLICODIGO,CPF) %>% 
                           summarize(BONUS=round(sum(BONUS),2)) %>% 
                           mutate(BONUS=round(sum(BONUS),2)/4), CARTOES_ALELO_0322 %>% 
                           select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="OTICA LINO 213 02/22") %>%
  mutate(CLIENTE='213') %>%  mutate(GRUPO='') 

View(PAG_213_0222)



### ===========================================================================================

##  SQL 1419 OTICA LOOK 

CP_1419_0222 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=1419),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '02/01/2022' AND '02/28/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=159) ,-- AVANCE


PROD2 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=128 AND LEFT(PROCODIGO,2)='LD') -- UZ+
  
  SELECT 
     PDPRD.ID_PEDIDO,
      PEDDTBAIXA,
       CLICODIGO,
        GCLCODIGO,
         SETOR,
          PDPRD.PROCODIGO,
           PDPDESCRICAO,
            PEDAUTORIZOU,
             SUM(PDPQTDADE)QTD,
              SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
               CAST(20 AS DECIMAL(10,2)) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(5 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 


View(CP_1419_0222)
CP_1419_0222 %>% summarize(v=sum(BONUS))

### lista pedidos  


LIST_1419_0222<- CP_1419_0222 %>% mutate(CPF=rep(c("47751118091"), length.out=nrow(CP_1419_0222))) %>% 
mutate(OBS="1419 OTICA LOOK 02/21")

View(LIST_1419_0222)


## agrupa bonificação CPf

CP_1419_0222 %>% group_by(CLICODIGO,CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

### pagamentos  

PAG_1419_0222 <- left_join(LIST_1419_0222
                           %>%  group_by(CLICODIGO,CPF) %>% 
                             summarize(BONUS=round(sum(BONUS),2)) , CARTOES_ALELO_0322 %>% 
                             select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="1419 OTICA LOOK 01/22") %>% 
  mutate(CLIENTE='1419') %>%  mutate(GRUPO='') 


View(PAG_1419_0222)

## ================================================================================


# SQL 305 GARUVA


CP_305_0222 <-dbGetQuery(con2,"
                           WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO WHERE C.CLICODIGO=305),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,GCLCODIGO,SETOR,PEDID.CLICODIGO,CLINOMEFANT,PEDAUTORIZOU 
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA BETWEEN '02/01/2022' AND '02/28/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=159), -- AVANCE

PROD2 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=158), -- ACTUALITE

PROD3 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=128), -- UZ+

PROD4 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=135) -- IMAGEM

SELECT  DISTINCT PDPRD.ID_PEDIDO,
          PEDDTBAIXA,
           CLICODIGO,
            GCLCODIGO,
             SETOR,
              PDPRD.PROCODIGO,
               PDPDESCRICAO,
                PEDAUTORIZOU,
                 SUM(PDPQTDADE)QTD,
                  SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                   CAST(40 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
DISTINCT PDPRD.ID_PEDIDO,
          PEDDTBAIXA,
           CLICODIGO,
            GCLCODIGO,
             SETOR,
               PDPRD.PROCODIGO,
               PDPDESCRICAO,
                PEDAUTORIZOU,
                  SUM(PDPQTDADE)QTD,
                   SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
                    CAST(30 AS INTEGER) BONUS

FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
DISTINCT PDPRD.ID_PEDIDO,
PEDDTBAIXA,
CLICODIGO,
GCLCODIGO,
SETOR,
PDPRD.PROCODIGO,
PDPDESCRICAO,
 PEDAUTORIZOU,
SUM(PDPQTDADE)QTD,
SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
CAST(20 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
DISTINCT PDPRD.ID_PEDIDO,
PEDDTBAIXA,
CLICODIGO,
GCLCODIGO,
SETOR,
PDPRD.PROCODIGO,
PDPDESCRICAO,
PEDAUTORIZOU,
SUM(PDPQTDADE)QTD,
SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
CAST(10 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2")  %>%  
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF))


View(CP_305_0222)

CP_305_0222 %>% summarize(v=sum(BONUS))


### lista pedidos

LIST_305_0222 <- CP_305_0222 %>% 
  mutate(CPF=rep(c("66655072972"), length.out=nrow(CP_305_0222))) %>% 
  mutate(OBS="305 OTICA GARUVA 02/22")

View(LIST_305_0222)


### pagamentos

PAG_305_0222 <- left_join(LIST_305_0222 %>% group_by(CPF) %>% 
                            summarize(BONUS=round(sum(BONUS),2)),
                          CARTOES_ALELO_0322 %>% 
                            select(NSERIE,CPF),by="CPF") %>% .[,c(3,1,2)] %>% 
  mutate(OBS="305 OTICA GARUVA 02/22")  %>% 
  mutate(CLIENTE='305') %>% 
  mutate(GRUPO='') 

View(PAG_305_0222)
PAG_305_0222 %>% summarize(v=sum(BONUS)) 

## =============================================================================================================         

# SQL G121 RINALDI

CP_G121_0222 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON 
       C.CLICODIGO=A.CLICODIGO WHERE GCLCODIGO=121),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU  
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA BETWEEN '02/01/2022' AND '02/28/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND (PRODESCRICAO LIKE '%X TRACK%' OR PRODESCRICAO LIKE '%4D%' OR PRODESCRICAO LIKE '%XCLUSIVE%')),

PROD2 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND PRODESCRICAO LIKE '%X DESIGN%'),

PROD3 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND PRODESCRICAO LIKE '%E DESIGN%'),

PROD4 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND (PRODESCRICAO LIKE '%COMFORT%' OR PRODESCRICAO LIKE '%LIBERTY%') AND LEFT(PROCODIGO,2)='LD'),
 
PED_PROMO_PAP AS (SELECT P.ID_PEDIDO ID_PEDIDO_PROMO FROM PDPRD P
 INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
   WHERE PROCODIGO='PAP'),

PED_PROMO_PLUGIN AS (SELECT ID_PEDIDPROMOCAO ID_PEDIDO_PROMO FROM PEDIDPROMO P
   INNER JOIN PD ON P.ID_PEDIDPROMOCAO=PD.ID_PEDIDO),

PED_PROMO_UNION AS (SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PAP UNION
SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PLUGIN)

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD2.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(50 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PROD3.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(40 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION


SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD4.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(30 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2
                      
 ") %>%
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF)) %>% 
  mutate(CPF=sub("\\,", '',CPF)) 

View(CP_G121_0222)

CP_G121_0222 %>% summarize(v=sum(VRVENDA))

CP_G121_0222 %>% summarize(v=sum(BONUS))

### lista pedidos  

LIST_G121_0222 <- CP_G121_0222 %>%  mutate(OBS="RINALDI G121 02/22")


### pagamentos

PAG_G121_0222 <- left_join(CP_G121_0222 %>% group_by(CPF) %>% summarize(BONUS=round(sum(BONUS),2)),
                           CARTOES_ALELO_0322 %>% 
                             select(NSERIE,CPF),by="CPF") %>% 
  .[,c(3,1,2)] %>% 
  mutate(OBS="RINALDI G121 02/22") %>% 
  mutate(CLIENTE='') %>%  mutate(GRUPO='121') 

View(PAG_G121_0222)

PAG_G121_0222 %>% summarize(v=sum(BONUS))



##  SQL 2183 OTICA MADRID --- outros produtos

CP_2183_0222_2 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=2183),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '02/01/2022' AND '02/28/2022' AND PEDSITPED <>'C'),

PROD4 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=159) ,-- AVANCE

PROD5 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=158) ,-- ACTUALITE

PROD6 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=128), -- UZ+
  
PROD7 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=135 AND LEFT(PROCODIGO,2)='LD') -- IMAGEM DIGITAL


SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(80 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD4 ON PDPRD.PROCODIGO=PROD4.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(70 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD5 ON PDPRD.PROCODIGO=PROD5.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(50 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD6 ON PDPRD.PROCODIGO=PROD6.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(30 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD7 ON PDPRD.PROCODIGO=PROD7.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 


View(CP_2183_0222_2)
CP_2183_0222_2 %>% summarize(v=sum(BONUS))
CP_2183_0222_2 %>% filter(nchar(CPF)==11) %>% summarize(v=sum(BONUS))

### lista pedidos  


LIST_2183_0222_2<- CP_2183_0222_2 %>% filter(nchar(CPF)==11) %>%  mutate(OBS="2183 OTICA MADRID OUTROS 02/22")
View(LIST_2183_0222_2)


## agrupa bonificação CPf

CP_2183_0222_2 %>% group_by(CLICODIGO,CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

### pagamentos  

PAG_2183_0222_2 <- left_join(CP_2183_0222_2 %>% 
                               filter(nchar(CPF)==11) %>%  group_by(CLICODIGO,CPF) %>% 
                               summarize(BONUS=round(sum(BONUS),2)) , CARTOES_ALELO_0322 %>% 
                               select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="2183 OTICA MADRID OUTROS 02/22") %>% 
  mutate(CLIENTE='2183') %>%  mutate(GRUPO='') 


View(PAG_2183_0222_2)


## =============================================================================================================         

# SQL 206 RH

CP_206_0921_0222 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON 
       C.CLICODIGO=A.CLICODIGO WHERE C.CLICODIGO=206),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,SETOR,CLINOMEFANT,PEDAUTORIZOU  
FROM PEDID 
INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
WHERE PEDDTBAIXA BETWEEN '09/01/2021' AND '02/28/2022' AND PEDSITPED <>'C'),

PROD1 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND PRODESCRICAO LIKE '%X DESIGN%'),

PROD2 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND PRODESCRICAO LIKE '%E DESIGN%'),

PROD3 AS (SELECT PROCODIGO,PRODESCRICAO FROM PRODU WHERE MARCODIGO=57 AND (PRODESCRICAO LIKE '%COMFORT%' OR PRODESCRICAO LIKE '%LIBERTY%') AND LEFT(PROCODIGO,2)='LD'),
 
PED_PROMO_PAP AS (SELECT P.ID_PEDIDO ID_PEDIDO_PROMO FROM PDPRD P
 INNER JOIN PD ON P.ID_PEDIDO=PD.ID_PEDIDO
   WHERE PROCODIGO='PAP'),

PED_PROMO_PLUGIN AS (SELECT ID_PEDIDPROMOCAO ID_PEDIDO_PROMO FROM PEDIDPROMO P
   INNER JOIN PD ON P.ID_PEDIDPROMOCAO=PD.ID_PEDIDO),

PED_PROMO_UNION AS (SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PAP UNION
SELECT ID_PEDIDO_PROMO FROM PED_PROMO_PLUGIN)

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD1.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(40 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
       PROD2.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(40 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PROD3.PROCODIGO,
        PDPDESCRICAO,
        PEDAUTORIZOU,
          SUM(PDPQTDADE)QTD,
           SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
            CAST(20 AS INTEGER) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
LEFT OUTER JOIN PED_PROMO_UNION ON PDPRD.ID_PEDIDO=PED_PROMO_UNION.ID_PEDIDO_PROMO
WHERE PED_PROMO_UNION.ID_PEDIDO_PROMO IS NULL
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 
                      
 ") %>%
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF)) %>% 
  mutate(CPF=sub("\\,", '',CPF)) 

View(CP_206_0921_0222)

CP_206_0921_0222 %>% summarize(v=sum(VRVENDA))

CP_206_0921_0222 %>% summarize(v=sum(BONUS))

### lista pedidos  

LIST_206_0921_0222 <- CP_206_0921_0222 %>% 
  mutate(CPF=rep(c("06850418912"), length.out=nrow(CP_206_0921_0222))) %>% 
  mutate(OBS="206 OTICA RH 09/21 - 02/22")


### pagamentos

PAG_206_0921_0222 <- left_join(LIST_CP_206_0921_0222 %>% group_by(CPF) %>% summarize(BONUS=round(sum(BONUS),2)),
                           CARTOES_ALELO_0322 %>% 
                             select(NSERIE,CPF),by="CPF") %>% 
  .[,c(3,1,2)] %>% 
  mutate(OBS="206 OTICA RH 09/21 - 02/22") %>% 
  mutate(CLIENTE='206') %>%  mutate(GRUPO='') 

View(PAG_206_0921_0222)


### ===========================================================================================

##  SQL 2183 OTICA MADRID -- Somente Insigne 

CP_2183_0222_1 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=2183),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '02/01/2022' AND '02/28/2022' AND PEDSITPED <>'C'),
       
PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%VISION%') ,-- INSIGNE VISION       

PROD2 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%PERFECT%') ,-- INSIGNE PERFECT 

PROD3 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%MORE%') -- INSIGNE MORE 

SELECT 
     PDPRD.ID_PEDIDO,
      PEDDTBAIXA,
       CLICODIGO,
        GCLCODIGO,
         SETOR,
          PDPRD.PROCODIGO,
           PDPDESCRICAO,
            PEDAUTORIZOU,
             SUM(PDPQTDADE)QTD,
              SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
               CAST(120 AS DECIMAL(10,2)) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(100 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(90 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 


View(CP_2183_0222_1)
CP_2183_0222_1 %>% summarize(v=sum(BONUS))
CP_2183_0222_1 %>% filter(nchar(CPF)==11) %>% summarize(v=sum(BONUS))

### lista pedidos  

LIST_2183_0222_1 <- CP_2183_0222_1 %>% filter(nchar(CPF)==11) %>%  
  mutate(OBS="2183 OTICA MADRID INSIGNE 02/22")
View(LIST_2183_0222_1)


## agrupa bonificação CPf

CP_2183_0222_1 %>% group_by(CLICODIGO,CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

### pagamentos  

PAG_2183_0222_1 <- left_join(CP_2183_0222_1 %>% 
                               filter(nchar(CPF)==11) %>%  group_by(CLICODIGO,CPF) %>% 
                               summarize(BONUS=round(sum(BONUS),2)) , CARTOES_ALELO_0322 %>% 
                               select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="2183 OTICA MADRID INSIGNE 02/22") %>% 
  mutate(CLIENTE='2183') %>%  mutate(GRUPO='') 


View(PAG_2183_0222_1)



### ===========================================================================================

##  SQL G195 OTICA LUNA -- Somente Insigne retroativo

CP_G195_0821_0122 <- dbGetQuery(con2,"
WITH CLI AS (SELECT DISTINCT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR
  FROM CLIEN C
  INNER JOIN (SELECT CLICODIGO FROM CLIPROMO WHERE ID_PROMO=18)CLP ON C.CLICODIGO=CLP.CLICODIGO
  LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
  INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
   WHERE CLICLIENTE='S' AND C.GCLCODIGO=195),
  
FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
  
PED AS (SELECT ID_PEDIDO,PEDCODIGO,P.CLICODIGO,CLINOMEFANT,GCLCODIGO,PEDDTEMIS,SETOR,
PEDDTBAIXA,PEDORIGEM,TPCODIGO,PEDAUTORIZOU FROM PEDID P
   INNER JOIN FIS F ON P.FISCODIGO1=F.FISCODIGO
    INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
     WHERE PEDDTBAIXA BETWEEN '08/01/2021' AND '01/31/2022' AND PEDSITPED<>'C'),

AUX AS (SELECT PROCODIGO,PROCODIGO2,IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)CHAVE FROM PRODU
WHERE MARCODIGO=189 AND  PROTIPO<>'T'),

VALORES_PROMO AS (SELECT PROCODIGO,GRVALORES
FROM NGRUPOS 
 INNER JOIN GRUPOVALORES ON NGRUPOS.GRCODIGO=GRUPOVALORES.GRCODIGO
  WHERE NGRUPOS.GRCODIGO IN (125,127,129,158))
  
SELECT 
PD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
     GCLCODIGO,
      SETOR,
        PD.PROCODIGO,
         PDPDESCRICAO,
          PEDAUTORIZOU,
           CAST(LEFT(GRVALORES,3) AS DOUBLE PRECISION) BONUS,
            SUM(PDPQTDADE) QTD,
             SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA
              
  FROM PDPRD PD
   INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
    INNER JOIN AUX A ON PD.PROCODIGO=A.PROCODIGO
     INNER JOIN VALORES_PROMO ON PD.PROCODIGO=VALORES_PROMO.PROCODIGO 
      GROUP BY 1,2,3,4,5,6,7,8,9 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 


View(CP_G195_0821_0122)
CP_G195_0821_0122 %>% summarize(v=sum(BONUS))
CP_G195_0821_0122 %>% filter(nchar(CPF)==11) %>% summarize(v=sum(BONUS))

### lista pedidos  

LIST_G195_0821_0122 <- CP_G195_0821_0122 %>% filter(nchar(CPF)==11) %>%  
  mutate(OBS="G195 OTICAS LUNA INSIGNE 08/21 - 01/22")
View(LIST_G195_0821_0122)

LIST_G195_0821_0122_2 <- CP_G195_0821_0122 %>%  
  mutate(OBS="G195 OTICAS LUNA INSIGNE 08/21 - 01/22")
View(LIST_G195_0821_0122_2)


## agrupa bonificação CPf

CP_G195_0821_0122 %>% group_by(CLICODIGO,CPF) %>% 
  summarize(BONUS=round(sum(BONUS),2)) %>% 
  mutate(DATA=floor_date(Sys.Date(),"month") %m-% months(1)) 

### pagamentos  

PAG_G195_0821_0122 <- left_join(LIST_G195_0821_0122 %>% 
                                group_by(CLICODIGO,CPF) %>% 
                               summarize(BONUS=round(sum(BONUS),2)) , CARTOES_ALELO_0322 %>% 
                               select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="G195 OTICAS LUNA INSIGNE 08/21 - 01/22") %>% 
  mutate(CLIENTE='') %>%  mutate(GRUPO='G195') 


View(PAG_G195_0821_0122)

## =========================================================================================================


##  SQL 1390 OTICA TESTONI -- Somente Insigne retroativo

CP_1390_0122 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.CLICODIGO=1390),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '01/01/2022' AND '01/31/2022' AND PEDSITPED <>'C'),
       
PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%VISION%') ,-- INSIGNE VISION       

PROD2 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%PERFECT%') ,-- INSIGNE PERFECT 

PROD3 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%MORE%') -- INSIGNE MORE 

SELECT 
     PDPRD.ID_PEDIDO,
      PEDDTBAIXA,
       CLICODIGO,
        GCLCODIGO,
         SETOR,
          PDPRD.PROCODIGO,
           PDPDESCRICAO,
            PEDAUTORIZOU,
             SUM(PDPQTDADE)QTD,
              SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
               CAST(120 AS DECIMAL(10,2)) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(100 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(90 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) 


View(CP_1390_0122)
CP_1390_0122 %>% summarize(v=sum(BONUS))
CP_1390_0122  %>% summarize(v=sum(BONUS))

### lista pedidos  

LIST_1390_0122 <- CP_1390_0122 %>%  
  mutate(OBS="1390 OTICA TESTONI INSIGNE RETROATIVO 01/22")
View(LIST_1390_0122)


### pagamentos  

PAG_1390_0122 <- left_join(CP_1390_0122 %>% 
                               group_by(CLICODIGO,CPF) %>% 
                               summarize(BONUS=round(sum(BONUS),2)) , CARTOES_ALELO_0322 %>% 
                               select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="1390 OTICA TESTONI INSIGNE RETROATIVO 01/22") %>% 
  mutate(CLIENTE='1390') %>%  mutate(GRUPO='') 


View(PAG_1390_0122)

## ===================================================================
##  SQL G146 MARCIO PINHEITO -- Somente Insigne retroativo

CP_G146_1221_0122 <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),

CLI AS(SELECT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR FROM CLIEN C
       LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
       INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
       WHERE C.GCLCODIGO=146),

PD AS (SELECT ID_PEDIDO,PEDDTBAIXA,PEDID.CLICODIGO,GCLCODIGO,CLINOMEFANT,SETOR,PEDAUTORIZOU 
       FROM PEDID 
       INNER JOIN FIS ON PEDID.FISCODIGO1=FIS.FISCODIGO
       INNER JOIN CLI ON PEDID.CLICODIGO=CLI.CLICODIGO
       WHERE 
       PEDDTBAIXA BETWEEN '11/26/2021' AND '01/31/2022' AND PEDSITPED <>'C'),
       
PROD1 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%VISION%') ,-- INSIGNE VISION       

PROD2 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%PERFECT%') ,-- INSIGNE PERFECT 

PROD3 AS (SELECT PROCODIGO FROM PRODU WHERE MARCODIGO=189
AND PRODESCRICAO LIKE '%MORE%') -- INSIGNE MORE 

SELECT 
     PDPRD.ID_PEDIDO,
      PEDDTBAIXA,
       CLICODIGO,
        GCLCODIGO,
         SETOR,
          PDPRD.PROCODIGO,
           PDPDESCRICAO,
            PEDAUTORIZOU,
             SUM(PDPQTDADE)QTD,
              SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
               CAST(120 AS DECIMAL(10,2)) BONUS
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD1 ON PDPRD.PROCODIGO=PROD1.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(100 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD2 ON PDPRD.PROCODIGO=PROD2.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2 UNION

SELECT 
 PDPRD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
    GCLCODIGO,
     SETOR,
      PDPRD.PROCODIGO,
       PDPDESCRICAO,
        PEDAUTORIZOU,
         SUM(PDPQTDADE)QTD,
          SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA,
           CAST(90 AS DECIMAL(10,2)) BONUS
          
FROM
PDPRD
INNER JOIN PD ON PDPRD.ID_PEDIDO=PD.ID_PEDIDO
INNER JOIN PROD3 ON PDPRD.PROCODIGO=PROD3.PROCODIGO
GROUP BY 1,2,3,4,5,6,7,8 HAVING SUM(PDPQTDADE)>=2") %>% 
  mutate(CPF=sub("\\D+", '',PEDAUTORIZOU)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF)) %>% 
  mutate(CPF=sub("\\,", '',CPF)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) 

View(CP_G146_1221_0122)
CP_G146_1221_0122 %>% summarize(v=sum(BONUS))
CP_G146_1221_0122  %>% summarize(v=sum(BONUS))

### lista pedidos  

LIST_G146_1221_0122 <- CP_G146_1221_0122 %>%  
  mutate(OBS="G146 MARCIO PINHEIRO INSIGNE RETROATIVO 12/21 - 01/22")
View(LIST_G146_1221_0122)


### pagamentos  

PAG_G146_1221_0122<- left_join(CP_G146_1221_0122 %>% 
                             group_by(CLICODIGO,CPF) %>% 
                             summarize(BONUS=round(sum(BONUS),2)) , CARTOES_ALELO_0322 %>% 
                             select(NSERIE,CPF),by="CPF") %>% .[,c(4,2,3)] %>%
  mutate(OBS="G146 MARCIO PINHEIRO INSIGNE RETROATIVO 12/21 - 01/22") %>% 
  mutate(CLIENTE='') %>%  mutate(GRUPO='146') 


View(PAG_G146_1221_0122)


## =============================================================================================================         

## SQL CAMPANHAS INSIGNE 

CP_INSIGNE_0222 <-dbGetQuery(con2,"
WITH CLI AS (SELECT DISTINCT C.CLICODIGO,CLINOMEFANT,GCLCODIGO,SETOR
  FROM CLIEN C
  INNER JOIN (SELECT CLICODIGO FROM CLIPROMO WHERE ID_PROMO=18)CLP ON C.CLICODIGO=CLP.CLICODIGO
  LEFT JOIN (SELECT CLICODIGO,D.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI D
  INNER JOIN ZONA Z ON D.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
   WHERE CLICLIENTE='S'),
  
FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','SR','R')),
  
PED AS (SELECT ID_PEDIDO,PEDCODIGO,P.CLICODIGO,CLINOMEFANT,GCLCODIGO,PEDDTEMIS,SETOR,
PEDDTBAIXA,PEDORIGEM,TPCODIGO,PEDAUTORIZOU FROM PEDID P
   INNER JOIN FIS F ON P.FISCODIGO1=F.FISCODIGO
    INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
     WHERE PEDDTBAIXA BETWEEN '02/01/2022' AND '02/28/2022' AND PEDSITPED<>'C'),

AUX AS (SELECT PROCODIGO,PROCODIGO2,IIF(PROCODIGO2 IS NULL,PROCODIGO,PROCODIGO2)CHAVE FROM PRODU
WHERE MARCODIGO=189 AND PROTIPO<>'T'),

VALORES_PROMO AS (SELECT PROCODIGO,GRVALORES
FROM NGRUPOS 
 INNER JOIN GRUPOVALORES ON NGRUPOS.GRCODIGO=GRUPOVALORES.GRCODIGO
  WHERE NGRUPOS.GRCODIGO IN (125,127,129,158))
  
SELECT 
PD.ID_PEDIDO,
  PEDDTBAIXA,
   CLICODIGO,
     GCLCODIGO,
      SETOR,
        PD.PROCODIGO,
         PDPDESCRICAO,
          PEDAUTORIZOU,
           CAST(LEFT(GRVALORES,3) AS DOUBLE PRECISION) BONUS,
            SUM(PDPQTDADE) QTD,
             SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA
              
  FROM PDPRD PD
   INNER JOIN PED P ON PD.ID_PEDIDO=P.ID_PEDIDO
    INNER JOIN AUX A ON PD.PROCODIGO=A.PROCODIGO
     INNER JOIN VALORES_PROMO ON PD.PROCODIGO=VALORES_PROMO.PROCODIGO 
      GROUP BY 1,2,3,4,5,6,7,8,9 HAVING SUM(PDPQTDADE)>=2
")  %>% mutate(CPF=sub("\\D+", '', PEDAUTORIZOU))  %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% 
  mutate(CPF=sub("\\-", '',CPF)) %>% 
  mutate(CPF=sub("\\.", '',CPF)) %>% filter(CLICODIGO !=2183) 

View(CP_INSIGNE_0222) 


CP_INSIGNE_0222 %>% summarize(v=sum(BONUS))

### listagem pedidos    

#pedidos com CPF
LIST_INSIGNE_0222 <- CP_INSIGNE_0222 %>% filter(nchar(CPF)==11) %>% mutate(OBS="CAMPANHA INSIGNE 02/22")
View(LIST_INSIGNE_0222)

LIST_INSIGNE_213_0222 <-  CP_INSIGNE_0222 %>% filter(CLICODIGO==213) %>% 
  mutate(CPF=rep(c("91212766920","06528427984","02235457088","03336880904"), length.out=nrow(.))) %>% 
  mutate(OBS="CAMPANHA INSIGNE 02/22") 

LIST_INSIGNE_213_0222 %>% summarize(v=sum(BONUS))


LIST_INSIGNE_0222_2 <- union(LIST_INSIGNE_0222,LIST_INSIGNE_213_0222)
View(LIST_INSIGNE_0222_2)



#pedidos sem CPF
LIST_INSIGNE_0222_2 <- CP_INSIGNE_0222 %>% filter(nchar(CPF)<11) %>% mutate(OBS="CAMPANHA INSIGNE 01/22")
View(LIST_INSIGNE_0222_2)

LIST_INSIGNE_0222 %>% filter(CLICODIGO==213) %>% 
  mutate(CPF=rep(c("91212766920","06528427984","02235457088","03336880904"), length.out=nrow(.)))  
View(LIST_INSIGNE_0222)

LIST_INSIGNE_213  <- LIST_INSIGNE %>% filter(CLICODIGO==213) %>% 
  mutate(CPF=rep(c("91212766920","06528427984","02235457088","03336880904"), length.out=nrow(.))) 


## LISTAGEM SETORES

#pedidos sem CPF
LIST_INSIGNE_0222_3 <- CP_INSIGNE_0222 %>% filter(!CLICODIGO %in% c(213)) %>% 
  mutate(OBS="CAMPANHA INSIGNE 02/22")
View(LIST_INSIGNE_0222_3)

LIST_INSIGNE_213_0222 <-  CP_INSIGNE_0222 %>% filter(CLICODIGO==213) %>% 
  mutate(CPF=rep(c("91212766920","06528427984","02235457088","03336880904"), length.out=nrow(.))) %>% 
  mutate(OBS="CAMPANHA INSIGNE 02/22") 
View(LIST_INSIGNE_213_0222)


LIST_INSIGNE_0222_SETORES <- union(LIST_INSIGNE_0222_3,LIST_INSIGNE_213_0222) 

View(LIST_INSIGNE_0222_SETORES)


### Pagamentos


PAG_INSIGNE_0222 <- CP_INSIGNE_0222 %>% filter(nchar(CPF)==11) %>% 
  group_by(CLICODIGO,GCLCODIGO,CPF) %>% 
  summarize(BONUS=sum(BONUS)) %>% 
  left_join(.,CARTOES_ALELO_0322 %>% select(CPF,NSERIE),by="CPF") %>% 
  mutate(OBS="CAMPANHA INSIGNE 02/22") %>% 
  `colnames<-`(c("CLIENTE","GRUPO","CPF","BONUS","NSERIE","OBS")) %>% 
  .[,c(5,3,4,6,1,2)]

View(PAG_INSIGNE_0222)


## caso lino
PAG_INSIGNE_0222_213 <- CP_INSIGNE_0222 %>% filter(CLICODIGO==213) %>% 
  mutate(CPF=rep(c("91212766920","06528427984","02235457088","03336880904"), length.out=nrow(.))) %>%
  as.data.frame() %>% 
  group_by(CLICODIGO,GCLCODIGO,CPF) %>% 
  summarize(BONUS=sum(BONUS)) %>% mutate(BONUS=sum(BONUS)/4) %>% 
  left_join(.,CARTOES_ALELO_0322 %>% select(CPF,NSERIE),by="CPF") %>% 
  mutate(OBS="CAMPANHA INSIGNE 02/22 ") %>% 
  `colnames<-`(c("CLIENTE","GRUPO","CPF","BONUS","NSERIE","OBS")) %>% 
  .[,c(5,3,4,6,1,2)]
View(PAG_INSIGNE_0222_213)



PAG_INSIGNE_0222_2 <- union(PAG_INSIGNE_0222,PAG_INSIGNE_0222_213) 
View(PAG_INSIGNE_0222_2)

PAG_INSIGNE_0222_2 %>% as.data.frame() %>% summarize(v=sum(BONUS)) %>% View(
)


## =============================================================================================================         
### Pagamentos retroativos

## Pedidos não identificados        

LIST_RETRO_0122 <-read_sheet("15xhLcF_qHiV1nreXjrxm6sfeqrC9J2r9IYOAUhjMU0w",sheet = "PEDIDOS")  



LIST_RETRO_0122_2 <- LIST_RETRO_0122 %>% mutate(CPF=`IDENTIFICAR CPF`) %>% .[,-14] %>%         
  mutate(OBS="PAGAMENTO RETROATIVO PEDIDOS NAO IDENTIFICADOS 01/22")

View(LIST_RETRO_0122_2)  



PAG_RETRO_0122 <- LIST_RETRO_0122 %>%  
  group_by(`IDENTIFICAR CPF`,CLICODIGO,GCLCODIGO) %>% summarize(BONUS=sum(BONUS)) %>%  
  `colnames<-`(c("CPF","CLIENTE","GRUPO","BONUS")) %>% 
  as.data.frame() %>%
  left_join(.,CARTOES_ALELO_0322 %>% select(CPF,NSERIE),by="CPF") %>% 
  mutate(OBS="PAGAMENTO RETROATIVO PEDIDOS NAO IDENTIFICADOS 01/22") %>% .[,c(5,1,4,6,2,3)]
View(PAG_RETRO_0122)  

PAG_RETRO_0122 %>% summarize(v=sum(BONUS))

## RETROATIVO G210

setor4_1221_G210 <- read_sheet("1uhlO4yR-EeyRqUvPVeT9hwsS5_rG4r0rtA6XzTl4b6Y",sheet = "SEMCPF") %>% 
  as.data.frame() %>% 
  mutate(`IDENTIFICAR CPF`=sub("\\D+", '',`IDENTIFICAR CPF`)) %>% 
  mutate(`IDENTIFICAR CPF`=sub("\\.", '',`IDENTIFICAR CPF`)) %>% 
  mutate(`IDENTIFICAR CPF`=sub("\\-", '',`IDENTIFICAR CPF`)) %>% filter(GCLCODIGO==210)

setor4_1221_G210 %>% summarize(v=sum(BONUS))

LIST_RETRO_1221_G210 <- setor4_1221_G210 %>% mutate(CPF=`IDENTIFICAR CPF`) %>% .[,-14] %>%         
  mutate(OBS="PAGAMENTO RETROATIVO PEDIDOS NAO IDENTIFICADOS G210 12/21")

View(LIST_RETRO_1221_G210)



PAG_RETRO_1221_G210 <- setor4_1221_G210 %>%  
  group_by(`IDENTIFICAR CPF`,CLICODIGO,GCLCODIGO) %>% summarize(BONUS=sum(BONUS)) %>%  
  `colnames<-`(c("CPF","CLIENTE","GRUPO","BONUS")) %>% 
  as.data.frame() %>%
  left_join(.,CARTOES_ALELO_0322 %>% select(CPF,NSERIE),by="CPF") %>% 
  mutate(OBS="PAGAMENTO RETROATIVO PEDIDOS NAO IDENTIFICADOS G210 12/21") %>% .[,c(5,1,4,6,2,3)]
View(PAG_RETRO_1221_G210)  





## =============================================================================================================         
## =============================================================================================================         
### PAGAMENTOS FINAL  


PAG_ALL_0222 <-  rbind( 
  PAG_G139_0222, ## schroeder ok
  PAG_849_0222,  ## Vital ok
  PAG_157_0222, ## Dom bosco OK
  PAG_BC_G37_0222_4, ## Barbara K OK
  PAG_4295_0222, ## Lumita OK
  PAG_G45_0222,  ## Diniz OK
  PAG_360_0222,  ## Universal ok
  PAG_213_0222,  ## Lino OK
  PAG_1419_0222, ## Look OK
  PAG_305_0222,  ## Garuva OK
  PAG_G121_0222, ## rinaldi OK
  PAG_2183_0222_2, ## Madrid ok
  PAG_206_0921_0222, ## RH ok
  PAG_G195_0821_0122, ## Luna ok
  PAG_1390_0122,      ## Testoni ok
  PAG_G146_1221_0122, ## Marcio pinheiro ok
  PAG_INSIGNE_0222_2, ## insigne OK
  PAG_RETRO_0122,  ## retroativo OK
  PAG_RETRO_1221_G210
  ) 

View(PAG_ALL_0222)

PAG_ALL_0222 %>% summarize(v=sum(BONUS))


sheet_write(PAG_ALL_0222,ss="1qhhjfP6tEgQDV9UUl8F4-KPMexYU67gdYwj_-A7vMl4",sheet="PAGAMENTOS")  


## listagem lançamento Alelo

PAG_ALL_0222_2 <- PAG_ALL_0222 %>% group_by(CPF,NSERIE) %>% 
  summarize(BONUS=sum(BONUS))

View(PAG_ALL_0222_2)

PAG_ALL_0222_2 %>% summarize(v=sum(BONUS))


sheet_write(PAG_ALL_0222_2,ss="1qhhjfP6tEgQDV9UUl8F4-KPMexYU67gdYwj_-A7vMl4",sheet="ALELO2")  



## =============================================================================================================         
## =============================================================================================================         
### LISTAGEM FINAL  


LIST_ALL_0222 <-  rbind( 
  LIST_G139_0222,   ## schroeder ok
  LIST_849_0222,    ## Vital ok
  LIST_157_0222,    ## Dom bosco OK
  LIST_BC_G37_0222, ## Barbara K OK
  LIST_4295_0222,   ## Lumita OK
  LIST_G45_0222,    ## Diniz OK 
  LIST_360_0222,    ## Universal ok
  LIST_213_0222,    ## Lino OK
  LIST_1419_0222,
  LIST_305_0222,    ## Garuva  OK
  LIST_G121_0222,   ## rinaldi OK
  LIST_2183_0222_2, ## Madrid insigne ok
  LIST_206_0921_0222, ## RH 
  LIST_G195_0821_0122, ## Luna ok
  LIST_1390_0122,   ##testoni
  LIST_G146_1221_0122,  ## Marcio Pinheiro ok
  LIST_INSIGNE_0222_2, ## Insigne
  LIST_RETRO_0122_2,
  LIST_RETRO_1221_G210
) 


View(LIST_ALL_0222)


write.csv2(LIST_ALL_0222,file = "C:/Users/Repro/Documents/R/2022/CAMPANHAS/FEV/LIST_ALL_0222.CSV")

LIST_ALL_0222 %>% summarize(v=sum(BONUS))


sheet_write(LIST_ALL_0222,ss="1qhhjfP6tEgQDV9UUl8F4-KPMexYU67gdYwj_-A7vMl4",sheet="PEDIDOS")       


## =============================================================================================================         
## =============================================================================================================         
### RESUMO  

CP_TOTAL_0222 <- PAG_ALL_0222 %>% summarize(TOTAL=sum(BONUS))    

range_write("1qhhjfP6tEgQDV9UUl8F4-KPMexYU67gdYwj_-A7vMl4",data=CP_TOTAL_0222,sheet = "RESUMO",
            range = "A1")


CP_TOTAL_0222_CLIENTE <- PAG_ALL_0222 %>% filter(is.na(GRUPO)) %>% 
  group_by(CLIENTE) %>% summarize(TOTAL=sum(BONUS))

range_write("hhjfP6tEgQDV9UUl8F4-KPMexYU67gdYwj_-A7vMl4",data=CP_TOTAL_0222_CLIENTE,sheet = "RESUMO",
            range = "A5")

CP_TOTAL_0222_GRUPO <- PAG_ALL_0222 %>% filter(!is.na(GRUPO)) %>% 
  group_by(GRUPO) %>% summarize(TOTAL=sum(BONUS))

range_write("hhjfP6tEgQDV9UUl8F4-KPMexYU67gdYwj_-A7vMl4",data=CP_TOTAL_0222_GRUPO,sheet = "RESUMO",
            range = "D5")



## =============================================================================================================         
## =============================================================================================================         
### LISTAGEM SETORES 


LIST_ALL_SETORES_0222 <-  rbind( 
  LIST_G139_0222,     ## schroeder ok
  LIST_849_0222,      ## Vital ok
  LIST_157_0222,      ## Dom bosco OK
  LIST_BC_G37_0222_2, ## Barbara K OK
  LIST_4295_0222,     ## Lumita OK
  LIST_G45_0222,      ## Diniz OK 
  LIST_360_0222,      ## Universal ok
  LIST_213_0222,      ## Lino OK
  LIST_1419_0222,     ## lOOK OK  
  LIST_305_0222,      ## Garuva  OK
  LIST_G121_0222,     ## rinaldi OK
  LIST_2183_0222_2,   ## Madrid insigne ok
  LIST_206_0921_0222, ## RH 
  LIST_G195_0821_0122_2,## Luna ok
  LIST_1390_0122,     ##testoni
  LIST_G146_1221_0122,## Marcio Pinheiro ok
  LIST_INSIGNE_0222_SETORES,## Insigne
  LIST_RETRO_0122_2,
  LIST_RETRO_1221_G210
  
  
) 

View(LIST_ALL_SETORES_0222)


sheet_write(LIST_ALL_SETORES_0222,ss="1dirGCDZQmlNTnZfC_gQhiXKE9DAoRNc-2HNWkSfego4",sheet="DADOS")       





