library(tidyverse)
library(lubridate)
library(DBI)
library(googlesheets4)
con2 <- dbConnect(odbc::odbc(), "repro2")

montagem <- dbGetQuery(con2,"
WITH FIS AS (SELECT FISCODIGO FROM TBFIS WHERE FISTPNATOP IN ('V','R','SR')),
  
   CLI AS (SELECT DISTINCT C.CLICODIGO,CLINOMEFANT,CLICNPJCPF, SETOR,GCLCODIGO
FROM CLIEN C
LEFT JOIN (SELECT CLICODIGO,E.ZOCODIGO,ZODESCRICAO SETOR FROM ENDCLI E
LEFT JOIN (SELECT ZOCODIGO,ZODESCRICAO FROM ZONA WHERE ZOCODIGO IN (20,21,22,23,24,25,28)
)Z ON E.ZOCODIGO=Z.ZOCODIGO WHERE ENDFAT='S')A ON C.CLICODIGO=A.CLICODIGO
 WHERE CLICLIENTE='S' AND (C.CLICODIGO IN (959,46) OR 
 C.CLICODIGO IN (SELECT CLICODIGO FROM CLIEN WHERE GCLCODIGO IN (60,175,71)))),
   
   PED AS (SELECT ID_PEDIDO,
   P.CLICODIGO,GCLCODIGO,CLINOMEFANT,PEDDTBAIXA,CLICNPJCPF CNPJ,SETOR FROM PEDID P
   INNER JOIN FIS ON P.FISCODIGO1=FIS.FISCODIGO
      INNER JOIN CLI C ON P.CLICODIGO=C.CLICODIGO
      WHERE (PEDDTBAIXA >= '01.01.2022' AND PEDDTBAIXA <= 'TODAY' 
      OR PEDDTBAIXA >= '01.01.2021' AND PEDDTBAIXA <= 'TODAY')
      AND PEDSITPED<>'C' AND PEDLCFINANC IN ('S', 'L','N')),
      
    PROD AS (SELECT PROCODIGO FROM PRODU WHERE PROTIPO='M')  
   
   SELECT
   PEDDTBAIXA,
   EXTRACT (YEAR FROM PEDDTBAIXA) ANO,
    DECODE(EXTRACT (MONTH FROM PEDDTBAIXA),1,'JAN',2,'FEV',3,
    'MAR',4,'ABR',5,'MAI',6,'JUN',7,'JUL',8,'AGO',9,'SET',10,'OUT',11,'NOV',12,'DEZ') AS MES,
      CLICODIGO,
      CLINOMEFANT,
      GCLCODIGO,
       CNPJ,
       SETOR,
       P.PROCODIGO,
        IIF(PP.PROCODIGO IS NULL,NULL,'MONT') MONTAGEM,
        PDPDESCRICAO,
        SUM(PDPUNITLIQUIDO*PDPQTDADE)VRVENDA 
  FROM PDPRD P
  INNER JOIN PED ON P.ID_PEDIDO=PED.ID_PEDIDO
  INNER JOIN PROD PP ON P.PROCODIGO=PP.PROCODIGO
  GROUP BY 1,2,3,4,5,6,7,8,9,10,11") 


montagem %>% group_by(ANO,MES,CLICODIGO,GCLCODIGO) %>% 
  summarize(v=format(sum(VRVENDA),big.mark=",")) %>% View()

montagem %>% group_by(ANO,MES,GCLCODIGO) %>% 
  summarize(v=format(sum(VRVENDA),big.mark=",")) %>% View()

data <- montagem


range_write("16GeiCX5QwDMj2XwsiLxpAU8Jspu8WAGk26GtgSYtOOQ",data=data,sheet = "DADOS",
            range = "A1")
